### ISSUE TITLE
Failed to activate the solarized-light-syntax package

### ISSUE THREAD

**Issue by abhikc** [abe33/atom-pigments#107]
[Enter steps to reproduce below:]

1. OS X -> Click on Atom menu -> Preferences
2. Select Themes -> Pick any new theme to apply

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1

### Stack Trace

Failed to activate the solarized-light-syntax package

```
At this.editor.displayBuffer.getVisibleRowRange is not a function

TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function
  at pigments-markers.ColorBufferElement.updateMarkers (/Users/abhijitchoudhury/.atom/packages/pigments/lib/color-buffer-element.coffee:132:5)
  at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/abhijitchoudhury/.atom/packages/pigments/lib/color-buffer-element.coffee:112:6)
  at /Users/abhijitchoudhury/.atom/packages/pigments/lib/color-buffer-element.coffee:77:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at StyleManager.module.exports.StyleManager.addStyleElement (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:111:27)
  at StyleManager.module.exports.StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:80:14)
  at ThemePackage.module.exports.Package.activateStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:283:52)
  at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:229:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:45:28
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:41:24
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:37:97)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:323:52
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:753:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:545:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:215:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:490:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:497:24

```

### Commands

```
     -6:04.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-unity-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-light-syntax"
    ]
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.12
atom-material-ui, v0.6.3
color-picker, v2.0.13
java-importer, v1.4.1
language-mongodb, v0.2.0
linter-jshint, v1.2.1
pigments, v0.18.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @abhikc, sorry about that, as with #92 and [my comment](https://github.com/abe33/atom-pigments/issues/92#issuecomment-152462289) at the end, the issue comes from the package's custom elements that are not updated properly with the rest of the package, reloading Atom should do the trick here.

I plan to get rid of them soon to avoid this kind of issues in the future.

**Comment by abhikc** [comment]
Thank you very much.
