### ISSUE TITLE
Failed to activate the one-dark-ui package

### ISSUE THREAD

**Issue by Arkngl** [abe33/atom-pigments#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1

### Stack Trace

Failed to activate the one-dark-ui package

```
At this.editor.displayBuffer.getVisibleRowRange is not a function

TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function
  at pigments-markers.ColorBufferElement.updateMarkers (/Users/Alf/.atom/packages/pigments/lib/color-buffer-element.coffee:132:5)
  at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/Alf/.atom/packages/pigments/lib/color-buffer-element.coffee:112:6)
  at /Users/Alf/.atom/packages/pigments/lib/color-buffer-element.coffee:77:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at StyleManager.module.exports.StyleManager.addStyleElement (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:111:27)
  at StyleManager.module.exports.StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:80:14)
  at ThemePackage.module.exports.Package.activateStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:283:52)
  at ThemePackage.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:229:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:45:28
  at ThemePackage.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:41:24
  at ThemePackage.module.exports.ThemePackage.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-package.js:37:97)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:323:52
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:753:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:545:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:215:14)
  at ThemesPanel.module.exports.ThemesPanel.updateThemeConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:490:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/themes-panel.js:497:24

```

### Commands

```
     -7:25.1.0 python-nosetests:run (atom-text-editor.editor.is-focused)
     -7:16.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-monokai.theme-atom-dark-ui)
  2x -4:24.2.0 core:backspace (atom-text-editor#python-tools.pythonPath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-copy-on-select, v1.4.0
atom-monokai, v0.9.6
autocomplete-python, v0.9.4
color-picker, v2.0.13
emmet, vundefined
file-icons, v1.6.11
linter, v1.10.0
linter-clang, v3.3.0
linter-cpplint, v0.1.4
linter-javac, v1.2.0
linter-php, v1.0.5
linter-phpmd, v1.3.2
local-server-express, v0.3.1
minimap, v4.16.0
pigments, v0.18.1
python-nosetests, v0.2.0
python-tools, v0.6.5
run-in-browser, v0.1.3
run-in-terminal, v0.4.2
script-runner, v1.8.4
simple-drag-drop-text, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @Arkngl, do you still get the issue after reloading Atom? It looks like #107 to me.
