### ISSUE TITLE
Failed to activate the emmet package

### ISSUE THREAD

**Issue by pakchano** [abe33/atom-pigments#111]
If the Instalation of Emmet appears duplicated
1. Update Emmet
2. Uninstall one of them

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1

### Stack Trace

Failed to activate the emmet package

```
At this.editor.displayBuffer.getVisibleRowRange is not a function

TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function
  at pigments-markers.ColorBufferElement.updateMarkers (/Users/jan/.atom/packages/pigments/lib/color-buffer-element.coffee:132:5)
  at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/jan/.atom/packages/pigments/lib/color-buffer-element.coffee:112:6)
  at /Users/jan/.atom/packages/pigments/lib/color-buffer-element.coffee:77:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at StyleManager.module.exports.StyleManager.addStyleElement (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:111:27)
  at StyleManager.module.exports.StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app.asar/src/style-manager.js:80:14)
  at Package.module.exports.Package.activateStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:283:52)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:229:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -0:51 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.14
file-icons, v1.6.11
minimap, v4.16.0
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @pakchano, it looks like #107 for me, can you confirm it works again after a reload?

**Comment by pakchano** [comment]
Yes, @abe33 it works now. I solved the issue this way, but I didn't come back to the comment before your reply. Thank you.
