### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by aaromnido** [abe33/atom-pigments#113]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1

### Stack Trace

Uncaught TypeError: Cannot read property 'editor' of undefined

```
At /Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: Cannot read property 'editor' of undefined
    at BackgroundRenderer.module.exports.RegionRenderer.createRegion (/Users/aaromnido/.atom/packages/pigments/lib/renderers/region-renderer.coffee:46:41)
    at BackgroundRenderer.module.exports.RegionRenderer.renderRegions (/Users/aaromnido/.atom/packages/pigments/lib/renderers/region-renderer.coffee:36:21)
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/aaromnido/.atom/packages/pigments/lib/renderers/background.coffee:10:16)
    at pigments-color-marker.ColorMarkerElement.render (/Users/aaromnido/.atom/packages/pigments/lib/color-marker-element.coffee:48:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/Users/aaromnido/.atom/packages/pigments/lib/color-marker-element.coffee:66:8)
    at /Users/aaromnido/.atom/packages/pigments/lib/color-buffer-element.coffee:59:16
    at Array.forEach (native)
    at /Users/aaromnido/.atom/packages/pigments/lib/color-buffer-element.coffee:57:20
    at Emitter.module.exports.Emitter.emit (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:211:32
    at Emitter.module.exports.Emitter.emit (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:312:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1251:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1213:19)
    at /Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (/Users/aaromnido/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
```

### Commands

```
     -1:20.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:19.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:13.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:13.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:13.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:13.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -1:00.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:00.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:59.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14 core:save (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:cut (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
color-picker, v2.0.12
emmet, v2.3.14
emmet-snippets-compatibility, v1.0.0
file-icons, v1.6.9
gulp-snippets, v0.6.2
jquery-snippets, v11.0.0
language-cshtml, v0.1.1
language-liquid, v0.4.0
minimap, v4.16.0
pigments, v0.18.1
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @aaromnido, sorry for the late reply, is it an error you get every time  you open a file? Did it disappear after reloading Atom?

**Comment by aaromnido** [comment]
Hi abe,

Nope, The error didn't disappear when we restarted Atom.
For fix that, I uninstalled pigments plugin.
