### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by rulonder** [abe33/atom-pigments#114]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.18.1

### Stack Trace

Failed to activate the linter package

```
At this.editor.displayBuffer.getVisibleRowRange is not a function

TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function
    at pigments-markers.ColorBufferElement.updateMarkers (C:\Users\rauln\.atom\packages\pigments\lib\color-buffer-element.coffee:138:55)
    at pigments-markers.ColorBufferElement.editorConfigChanged (C:\Users\rauln\.atom\packages\pigments\lib\color-buffer-element.coffee:113:6)
    at C:\Users\rauln\.atom\packages\pigments\lib\color-buffer-element.coffee:77:8
    at Emitter.module.exports.Emitter.emit (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at StyleManager.module.exports.StyleManager.addStyleElement (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\style-manager.js:114:27)
    at StyleManager.module.exports.StyleManager.addStyleSheet (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\style-manager.js:83:14)
    at Package.module.exports.Package.activateStylesheets (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:221:58)
    at Package.module.exports.Package.activateNow (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:167:14)
    at C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:512:21)
    at C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:385:60
    at exit (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\rauln\AppData\Local\atom\app-1.2.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.10.0
color-picker, v2.0.13
file-icons, v1.6.9
highlight-selected, v0.10.1
imdone-atom, v1.1.39
language-docker, v1.1.3
linter, v1.11.1
linter-tslint, v0.5.0
minimap, v4.16.0
node-debugger, vundefined
pigments, v0.18.1
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @rulonder, please refer to #92 if you want explanations and details about the source of the issue. As for the solution, just restarting Atom should fix that.
