### ISSUE TITLE
Failed to load the flint package

### ISSUE THREAD

**Issue by malonehedges** [abe33/atom-pigments#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.19.0

### Stack Trace

Failed to load the flint package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'pigments-color-marker'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'pigments-color-marker'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/color-marker-element.coffee:86:10)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/color-marker-element.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/color-project.coffee:12:22)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/color-project.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/pigments.coffee:3:16)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/pigments/lib/pigments.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/malonehedges/.atom/packages/flint/lib/index.js:9:30)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:511:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
 11x -3:06.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:04.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:03.3.0 jumpy:toggle (atom-text-editor.editor.is-focused)
     -3:01.8.0 jumpy:a (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -3:01.7.0 jumpy:b (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -2:59.9.0 jumpy:toggle (atom-text-editor.editor.is-focused)
     -2:40.8.0 jumpy:d (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -2:40.8.0 jumpy:a (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -2:39.5.0 jumpy:toggle (atom-text-editor.editor.is-focused)
     -2:37.9.0 jumpy:d (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -2:37.8.0 jumpy:l (atom-text-editor.editor.is-focused.jumpy-jump-mode)
     -1:32.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:25.9.0 window:toggle-dev-tools (div.panels-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "advanced-new-file",
      "tool-bar",
      "tool-bar-main",
      "linter-coffeelint",
      "linter-jshint"
    ],
    "projectHome": "/Users/malonehedges/code/",
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-fusion-syntax, v1.1.0
atom-jade, v0.3.0
atom-pair, v2.0.10
autoclose-html, v0.19.0
autocomplete-emojis, v2.2.2
autocomplete-sass, v0.1.0
color-picker, v2.0.13
flint, v3.10.1
fold-comments, v0.5.0
fold-functions, v0.4.3
highlight-selected, v0.11.1
jumpy, v2.0.10
language-cjsx, v0.3.0
language-coffee-script-angular, v2.2.0
language-haml, v0.23.6
language-lua, v0.9.4
linter, v1.11.2
linter-htmlhint, v0.2.1
minimap, v4.16.1
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
new-file-plus, v0.2.1
nucleus-dark-ui, v0.6.11
pigments, v0.19.0
sync-settings, v0.6.0
xkcd-comics, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @malonehedges, does a restart helps or do you get this error on every start?

**Comment by malonehedges** [comment]
@abe33 Now I am getting #42 after restarting.

**Comment by abe33** [comment]
@malonehedges Even after running `apm install` in the package directory?

**Comment by C-Bouthoorn** [comment]
Bump @malonehedges

**Comment by malonehedges** [comment]
Haven't had an issue for a while with atom-pigments, can't remember what specifically fixed this. atom-pigments was frequently a source of my Atom issues but it has been working perfectly for a while now. Thanks for checking in @C-Bouthoorn
