### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getProject' of null

### ISSUE THREAD

**Issue by ChillOut05** [abe33/atom-pigments#118]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.19.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getProject' of null

```
At /C:/Users/ChillOut/.atom/packages/pigments/lib/pigments-provider.coffee:33

TypeError: Cannot read property 'getProject' of null
    at PigmentsProvider.module.exports.PigmentsProvider.getProject (file:///C:/Users/ChillOut/.atom/packages/pigments/lib/pigments-provider.coffee:19:27)
    at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (file:///C:/Users/ChillOut/.atom/packages/pigments/lib/pigments-provider.coffee:23:16)
    at C:\Users\ChillOut\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\ChillOut\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\ChillOut\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\ChillOut\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:252:19)
    at C:\Users\ChillOut\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
```

### Commands

```
     -0:40.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:21.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:21.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:21.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:21.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:21.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:09.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.0 core:undo (atom-text-editor.editor.is-focused)
     -0:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.2.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-todo",
      "language-toml",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "markdown-preview",
      "autocomplete-html",
      "autocomplete-css"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "D:\\Work"
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
emmet, vundefined
file-icons, v1.6.12
language-jade, v0.6.2
linter, v1.11.2
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jade, v0.3.2
linter-jshint, v1.2.1
minimap, v4.16.2
pigments, v0.19.0
Stylus, v1.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @ChillOut05, thank you for the report, can you tell me a bit more about the context? Did you disable pigments or something before that error occured?

**Comment by ChillOut05** [comment]
@abe33 thank you for the reply, but it seems like the error is gone know. Maybe there was some sort of conflict, but after restarting atom the problem is no longer detected. I'm sorry for disturbing you for nothing

**Comment by abe33** [comment]
@ChillOut05  No problem, thank you for keeping me updated on this.

I think I found why it could lead to this issue, I'll publish a patch soon.
