### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by zachrnolan** [abe33/atom-pigments#120]
[Enter steps to reproduce below:]

1. Installed atom-pigments from within Atom.

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.19.2

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /Users/zachnolan/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:14

TypeError: Cannot read property 'apply' of undefined
    at pigments-markers.Object.defineProperty.value [as attributeChangedCallback] (/Users/zachnolan/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:14:32)
    at /Users/zachnolan/.atom/packages/pigments/lib/color-buffer-element.coffee:84:22
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:605:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at pigments-markers.ColorBufferElement.setModel (/Users/zachnolan/.atom/packages/pigments/lib/color-buffer-element.coffee:78:36)
    at Object.createView (/Users/zachnolan/.atom/packages/pigments/lib/color-buffer-element.coffee:356:13)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:83:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:68:21)
    at /Users/zachnolan/.atom/packages/pigments/lib/color-project.coffee:270:36
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at ColorProject.module.exports.ColorProject.initializeBuffers (/Users/zachnolan/.atom/packages/pigments/lib/color-project.coffee:267:39)
    at new ColorProject (/Users/zachnolan/.atom/packages/pigments/lib/color-project.coffee:159:6)
    at Object.module.exports.activate (/Users/zachnolan/.atom/packages/pigments/lib/pigments.coffee:92:11)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:23.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.17
pigments, v0.19.2

# Dev
No dev packages
```

**Comment by marcio** [comment]
+1

**Comment by arestivo** [comment]
I'm getting the same error.

Atom version: v1.4.0-beta0-ed7283f (32-bit instaled from source)
Pigments version: v0.19.2
No other packages

**Comment by PuYart** [comment]
+1

**Comment by mitchmalone** [comment]
Yup

**Comment by tgaeta** [comment]
+1

**Comment by mistadikay** [comment]
+1

`Atom 1.4.0-beta0`
`pigments 0.19.2`

**Comment by suenot** [comment]
+1
Atom 1.3.1
pigments 0.19.2
windows 7
```
TypeError: Cannot read property 'apply' of undefined
    at pigments-color-marker.Object.defineProperty.value [as attributeChangedCallback] (C:\Users\suenot\.atom\packages\pigments\node_modules\atom-utils\lib\register-or-update-element.js:14:32)
    at pigments-markers.ColorBufferElement.updateSelections (file:///C:/Users/suenot/.atom/packages/pigments/lib/color-buffer-element.coffee:287:24)
    at file:///C:/Users/suenot/.atom/packages/pigments/lib/color-buffer-element.coffee:280:8
```

**Comment by calidion** [comment]
+1

**Comment by agucova** [comment]
+1
    Atom 1.2.4
    Pigments, v0.19.0
    OSX 10.11.11

**Comment by dagstuan** [comment]
+1

**Comment by gomsilruk** [comment]
+1

**Comment by yestoall** [comment]
+1

**Comment by abe33** [comment]
Thank you all for the feedback, looks like I screwed up the last version of atom-utils, I'll publish a patch asap

**Comment by abe33** [comment]
I just published a patch that bumps the version of atom-utils to the version with the fix.

**Comment by dagstuan** [comment]
I still have the issue with v0.19.3

**Comment by abe33** [comment]
@dagstuan after updating from within Atom?

**Comment by timpalander** [comment]
I Just installed Atom fresh and installed Pigments. I'm getting this error.

**Comment by abe33** [comment]
If you still get this error please verify that the version of the `atom-utils` module (located in the package's `node_modules` directory) is `0.9.2`. If not, remove the whole `node_modules` run `apm install` in the package directory.

**Comment by tgaeta** [comment]
Got an error after update; however, got it working by killing Atom and booting it back up.

Steps to reproduce:

1. Install pigments package
2. Open file containing hex values

Steps to fix:

1. Kill Atom and boot it back up
2. Open file containing hex values and see pigments working

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.19.3


### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At /Users/tonyg/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:14

TypeError: Cannot read property 'apply' of undefined
    at pigments-markers.Object.defineProperty.value [as attributeChangedCallback] (/Users/tonyg/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:14:32)
    at /Users/tonyg/.atom/packages/pigments/lib/color-buffer-element.coffee:84:22
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:605:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at pigments-markers.ColorBufferElement.setModel (/Users/tonyg/.atom/packages/pigments/lib/color-buffer-element.coffee:78:36)
    at Object.createView (/Users/tonyg/.atom/packages/pigments/lib/color-buffer-element.coffee:356:13)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:83:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:68:21)
    at /Users/tonyg/.atom/packages/pigments/lib/color-project.coffee:270:36
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:282:9)
    at ColorProject.module.exports.ColorProject.initializeBuffers (/Users/tonyg/.atom/packages/pigments/lib/color-project.coffee:267:39)
    at new ColorProject (/Users/tonyg/.atom/packages/pigments/lib/color-project.coffee:159:6)
    at Function.module.exports.ColorProject.deserialize (/Users/tonyg/.atom/packages/pigments/lib/color-project.coffee:102:9)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:41:29)
    at Object.module.exports.activate (/Users/tonyg/.atom/packages/pigments/lib/pigments.coffee:90:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
  2x -3:20.2.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -3:18.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:55.3.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -2:52.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:33.7.0 core:undo (atom-text-editor.editor.is-focused)
     -2:31.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:25.8.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:21.1.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -2:19.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:16.4.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -2:12.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:56.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:56 core:save (atom-text-editor.editor.is-focused)
     -0:34 settings-view:open (atom-text-editor.editor.is-focused)
     -0:13 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.13
language-haml, v0.23.13
pigments, v0.19.3

# Dev
No dev packages
```

**Comment by timpalander** [comment]
Ok this is weird. Here's how i fixed it.

- Uninstalled pigments
- Install minimap-pigments
- install pigments
- Restart Atom

**Comment by abe33** [comment]
I have the feeling there are more and more weird things with packages update lately.

**Comment by afomi** [comment]
+1 @timpalander - this resolved the issue for me as well - although I am not clear as to why.

**Comment by jenskanis** [comment]
+1

**Comment by nhhockeyplayer** [comment]
I am receiving this now and 
npm info atom-utils 
0.9.2 latest

Uncaught TypeError: Cannot read property 'apply' of undefined

here is my bundle app.js:13047
  var defineOrOverrideReflectProperty = function (key, shim) {
    if (!ES.IsCallable(globals.Reflect[key])) {

Just trying to load my index.html which does what angular2 quikstart says to load

html complains that System is not defined

<script>
	System.config({
		packages: {

These issues lists are the longest... it'd be nice if things were short and concise with steps to resolve instead of... 

Any ideas at this point? my bundles look legit... I am even using the order feature of gulp-bundle-assets

**Comment by abe33** [comment]
@nhhockeyplayer, hi there, sorry the inconvenience, do you min providing me with the full error stack you encounter?
