### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by BlaM** [abe33/atom-pigments#13]
[Enter steps to reproduce below:]

Not sure if the crash/stack trace below actually belongs to the problem I'm observing, but it was triggered ONCE by the behavior I see here:

1. Create a new file and save as freeze.css
2. Type ".a"
3. Editor locks up.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'filter' of undefined

```
At C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:244

TypeError: Cannot read property 'filter' of undefined
  at ColorProject.module.exports.ColorProject.getColorVariables (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:244:38)
  at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (C:\Users\ddeobald\.atom\packages\pigments\lib\pigments-provider.coffee:27:28)
  at C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:254:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:233:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:221:19)
  at C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```

### Commands

```
  2x -0:40.4.0 click (div.title)
     -0:38.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.5.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:37.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.5.0 click (a.btn-issue.btn.btn-error)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "js-refactor",
      "linter-eslint",
      "deprecation-cop",
      "recent-projects",
      "recent-files",
      "conceal",
      "less-than-slash",
      "emmet"
    ]
  },
  "pigments": {
    "sourceNames": [
      "**/*.styl",
      "**/*.stylus",
      "**/*.less",
      "**/*.sass",
      "**/*.scss",
      "**/*.css"
    ],
    "markerType": "underline"
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
atom-html-preview, v0.1.6
composer, v0.3.1
highlight-selected, v0.9.3
html-id-class-snippets, v1.4.1
language-sql-mysql, v0.3.1
less-autocompile, v1.0.0
linter, v0.12.2
linter-htmlhint, v0.0.15
linter-jshint, v0.1.4
linter-jsonlint, v0.1.3
linter-php, v0.0.12
minimap, v4.8.0
minimap-highlight-selected, v4.2.3
open-recent, v2.2.2
pigments, v0.2.1
pretty-json, v0.3.3
project-manager, v1.15.5
select-line, v0.16.0
select-rectangle, v1.0.2
uuidgen, v1.2.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Not sure why you added `**/*.css` to the source names setting, as actually CSS files aren't source for project variables (this is a feature that make sense for pre-processors, not really for plain old CSS).

Can you tell me if you get the same behavior when you remove `**/*.css` from the setting?

**Comment by BlaM** [comment]
I removed the *.css entry and tried again:

- When I type ".a" in a new .css file I get now get the stack trace from above
- When I type ".a" in a new .less file the editor freezes up ("Editor is not responding...")

**Comment by BlaM** [comment]
Okay, just noticed something else: It only happens when I'm in my project and not if I open another directory. So I guess this is caused by one of the CSS files in the project directory?

My one CSS so far is extremely minimalistic, but I have these "vendor" dependencies:

* bootstrap 3.3.4
* bootstrap-datepicker 1.4.0
* font-awesome 4.3.0
* summernote 0.6.6

**Comment by abe33** [comment]
Hmm, can you try something for me? 
In the devtools console can you run the folowing code and put the output of the second line in a gist: 

```js
// This line will retrieve the pigments project object
pigments = atom.packages.getActivePackage('pigments').mainModule; project = pigments.getProject()

// This line will print every variables in the project with their name, value and relative path
project.getVariables().map(function(v,i){ return i + ' - ' + v.name + ' = ' + v.value + ' (' + atom.project.relativize(v.path) + ')' }).join('\n')
```
I would like to confirm whether there's garbage in the project's variables list.

**Comment by BlaM** [comment]
Tried it with these results:

- If I start Atom freshly (in the project directory) and execute the code above: getVariables() returns "undefined" -> map() fails.

- If I start Atom freshly, create a CSS file, type .a (gives me the "property 'filter' of undefined" error message) and THEN execute your code above the console locks up. I tried leaving the ".map()" away and I get an array of 8593 elements (Object "ProjectVariable"). I tried to "JSON.stringify" the result of getVariables(), but that freezes the console, too.

**Comment by BlaM** [comment]
I just updated the package to 0.3.0 while having it disabled. Then when I tried to enable the package I get...
 
### Stack Trace

Failed to activate the pigments package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
  at ColorProject.module.exports.ColorProject.getVariableByName (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:237:5)
  at C:\Users\ddeobald\.atom\packages\pigments\lib\color-buffer.coffee:83:27
  at Array.map (native)
  at ColorBuffer.module.exports.ColorBuffer.restoreMarkersState (C:\Users\ddeobald\.atom\packages\pigments\lib\color-buffer.coffee:77:6)
  at new ColorBuffer (C:\Users\ddeobald\.atom\packages\pigments\lib\color-buffer.coffee:50:8)
  at ColorProject.module.exports.ColorProject.colorBufferForEditor (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:144:55)
  at C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:125:17
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\workspace.js:267:9)
  at ColorProject.module.exports.ColorProject.initializeBuffers (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:124:39)
  at new ColorProject (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:44:6)
  at Function.module.exports.ColorProject.deserialize (C:\Users\ddeobald\.atom\packages\pigments\lib\color-project.coffee:21:9)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\deserializer-manager.js:42:29)
  at Object.module.exports.activate (C:\Users\ddeobald\.atom\packages\pigments\lib\pigments.coffee:76:43)
  at Package.module.exports.Package.activateNow (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:303:19
  at C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:574:20
  at Emitter.module.exports.Emitter.emit (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:736:29)
  at Config.module.exports.Config.setRawValue (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:551:19)
  at Config.module.exports.Config.set (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:343:12)
  at Package.module.exports.Package.enable (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:148:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\ddeobald\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
  2x -0:47.9.0 click (div.title)
     -0:41.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:39.1.0 click (div.close-icon)
     -0:21.9.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:14 core:delete (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 click (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "js-refactor",
      "linter-eslint",
      "deprecation-cop",
      "recent-projects",
      "recent-files",
      "conceal",
      "less-than-slash",
      "emmet"
    ]
  },
  "pigments": {
    "markerType": "underline"
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
atom-beautify, v0.27.1
atom-html-preview, v0.1.6
composer, v0.3.1
highlight-selected, v0.9.3
html-id-class-snippets, v1.4.1
language-sql-mysql, v0.3.1
less-autocompile, v1.0.0
linter, v0.12.2
linter-htmlhint, v0.0.15
linter-jshint, v0.1.4
linter-jsonlint, v0.1.3
linter-php, v0.0.12
minimap, v4.9.0
minimap-highlight-selected, v4.2.3
open-recent, v2.2.2
pigments, v0.3.0
pretty-json, v0.3.3
project-manager, v1.15.5
select-line, v0.16.0
select-rectangle, v1.0.2
uuidgen, v1.2.0

# Dev
No dev packages
```

**Comment by BlaM** [comment]
The package is now active, but ".getVariables()" always seems to return undefined, even after editing the .css file

**Comment by abe33** [comment]
Can you try running the `pigments:reload` command?

**Comment by BlaM** [comment]
Same result. Ends up with "undefined" as returned value of getVariables();

**Comment by abe33** [comment]
And what gives `project.getPaths()`? Maybe I've forgot to initializes the variables array when there's no source paths (if you only work with CSS it could occurs).

**Comment by BlaM** [comment]
Took some time (does it need time to initialize? I'm working on an SMB-Share), but getVariables now returns an array.

Calling JSON.stringify on that thing still does not work, though.

 getPaths() returns an array of 278 file paths.  (LESS and SCSS files).

**Comment by abe33** [comment]
> does it need time to initialize?

Yes, on the first load, or when you use the reload command, it has to find and scan all the source files in the project. So if your project is quite huge it can take some time. That's why `project.initialize()` returns a promise, because it's hard to predict when all the variables will be available.

I'll be interested in a description of your project structure, to see if I can reproduce that on my computer. By the structure, I mean what dependencies do you have. Does the less/scss files comes from libraries that I can find on the web, etc.

I was considering implementing a guard for when a project have more that X sources paths (X being defined in a setting) so that really big projects that have dozens of files but only a few that actually defines variables could be managed with more granularity. The guard would warn you that the project goes past the threshold and offer you to specify manually the variables sources instead. How do you feel about this kind of alert as a user? Do you think it make sense?

**Comment by BlaM** [comment]
Okay, maybe it's the "loading everything" that causes the problem then. So in that case an emergency exit would totally make sense. 

The project I'm currently working on is not so big - but it actually took me until now to notice that I'm not working in the "project" itself, but in it's parent folder (i.e. my current project resides in y:\dominik\myproject, but I started Atom in y:\dominik). And that directory has a LOT of stuff - which may be okay on an SSD, but not over a network connection.

I now moved the root folder to ...\myproject - and the first call still needs some time, but it comes to a final result and doesn't freeze the editor until the moment it gives up on itself and asks if I want to continue waiting.

**Comment by abe33** [comment]
Version 0.5.0 should have addressed most of the performances issues, please let me know if things improved for you.

**Comment by BlaM** [comment]
It doesn't freeze anymore, but in my huge "all in one folder" creating a CSS file halted the editor for several seconds. Not sure what caused this. May be pigment, may be Atom itself or may be any other plugin.

But total result: No major problems anymore. :+1:

**Comment by abe33** [comment]
@BlaM: It'll be interesting if you can try to profile this situation, Maybe pigments is at fault. I haven't implemented a way to handle newly added files except by listening to the change of path on the buffer (which mean it only works when you create a new buffer and then save it, not when the file is created from the tree-view)

**Comment by BlaM** [comment]
What I actually did was press CTRL+N to create a new file (not even saved) and then changed it to CSS (bottom right corner in Atom Window).

And just for reference: My "big" directory is a total of ~25.000 files in ~5.000 sub-folders.

**Comment by abe33** [comment]
Hmm, not sure about what could possibly go wrong. If you know how to use the chrom devtools and have some time I would like you to try profiling this situation to see where the bottleneck is.
