### ISSUE TITLE
Atom error when splitting color palette

### ISSUE THREAD

**Issue by marpala** [abe33/atom-pigments#139]
[Enter steps to reproduce below:]

1. Right click on Pigment's color palette tab
2. Choose Split right (or left, etc.)

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught TypeError: item.serialize is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:401

TypeError: item.serialize is not a function
    at atom-tabs.TabBarView.copyItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:401:133)
    at atom-tabs.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:391:31)
    at Object.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:127:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:78:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:02.4.0 tabs:split-right (li.tab.sortable.active.right-clicked)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "foldingtext-for-atom",
      "linter-rubocop",
      "linter-pylint"
    ],
    "ignoredNames": [
      "node_modules",
      ".sass-cache",
      "CVS",
      ".git",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".hg",
      "config.codekit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-jade, v0.3.0
color-picker, v2.1.1
highlight-selected, v0.11.2
less-than-slash, v0.12.3
linter, v1.11.3
linter-csslint, v1.2.0
linter-jshint, v1.3.0
pigments, v0.23.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by marpala** [comment]
Also related to splitting the palette view:

![screen_shot_2016-02-06_at_12_53_43](https://cloud.githubusercontent.com/assets/439204/12866531/34d0ffb6-ccd1-11e5-92aa-84d653d4bfed.jpg)
![screen_shot_2016-02-06_at_12_53_57](https://cloud.githubusercontent.com/assets/439204/12866532/36cb25e4-ccd1-11e5-95f8-b587ef998823.jpg)

Because of the error I posted above, the only way to split the palette is to split the other tabs instead but doing so will cause the palette to show those visual glitches.

**Comment by abe33** [comment]
Hi @marpala, thanks for the report. I think I never really took care of that, but I should, as well as making sure that the view updates when new variables as found. Look like it's time I give it some love.
