### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by buckyoung** [abe33/atom-pigments#14]
Reproduce:
1. Type "\" in ignored scopes (in Settings)

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.3.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern

```
At /Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:371

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
  at new RegExp (native)
  at /Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:371:28
  at Array.some (native)
  at ColorBuffer.module.exports.ColorBuffer.markerScopeIsIgnored (/Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:370:20)
  at /Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:331:41
  at Array.filter (native)
  at ColorBuffer.module.exports.ColorBuffer.findValidColorMarkers (/Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:330:35)
  at pigments-markers.ColorBufferElement.updateMarkers (/Users/buckyoung/.atom/packages/pigments/lib/color-buffer-element.coffee:104:28)
  at /Users/buckyoung/.atom/packages/pigments/lib/color-buffer-element.coffee:39:65
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/buckyoung/.atom/packages/pigments/lib/color-buffer.coffee:47:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:557:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:190:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:236:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1111:25

```

### Commands

```
     -6:00.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:59.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:58.7.0 core:cut (atom-text-editor.editor.is-focused)
     -5:56.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:55.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -5:53.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:52.3.0 core:undo (atom-text-editor.editor.is-focused)
     -5:51.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -5:51.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:50.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -5:38 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -5:33.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:33.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:19 settings-view:open (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:backspace (atom-text-editor#pigments.ignoredScopes.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "timecop",
      "metrics",
      "language-mustache",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-make",
      "autocomplete",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "ask-stack",
      "atom-color-highlight",
      "autocomplete-plus",
      "merge-conflicts"
    ]
  },
  "pigments": {
    "delayBeforeScan": 3000,
    "groupPaletteColors": "by file",
    "sortPaletteColors": "by name",
    "ignoredScopes": [
      "\\."
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-diff-details, v0.18.0
highlight-selected, v0.9.3
linter, v0.12.2
linter-jshint, v0.1.4
linter-scss-lint, v0.0.14
minimap, v4.9.0
minimap-git-diff, v4.1.3
pigments, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, I had encountered this one too, I'll add a trap for that case in the next patch
