### ISSUE TITLE
Uncaught TypeError: Cannot read property 'luma' of undefined

### ISSUE THREAD

**Issue by joseluisq** [abe33/atom-pigments#148]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: "Fedora release
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.24.1

### Stack Trace

Uncaught TypeError: Cannot read property 'luma' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

TypeError: Cannot read property 'luma' of undefined
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/home/joseluis/.atom/packages/pigments/lib/renderers/background.coffee:12:26)
    at pigments-color-marker.ColorMarkerElement.render (/home/joseluis/.atom/packages/pigments/lib/color-marker-element.coffee:63:46)
    at pigments-color-marker.ColorMarkerElement.checkScreenRange (/home/joseluis/.atom/packages/pigments/lib/color-marker-element.coffee:84:8)
    at /home/joseluis/.atom/packages/pigments/lib/color-buffer-element.coffee:56:16
    at Array.forEach (native)
    at /home/joseluis/.atom/packages/pigments/lib/color-buffer-element.coffee:54:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:219:32
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/share/atom/resources/app.asar/src/display-buffer.js:1227:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1189:19)
    at /usr/share/atom/resources/app.asar/src/display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:412:27)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:572:12)
    at TextBuffer.module.exports.TextBuffer.delete (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:675:19)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:911:35
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1244:26)
    at TextEditor.module.exports.TextEditor.moveLineUp (/usr/share/atom/resources/app.asar/src/text-editor.js:864:19)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:move-line-up (/usr/share/atom/resources/app.asar/src/register-default-commands.js:537:21)
    at /usr/share/atom/resources/app.asar/src/register-default-commands.js:576:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1244:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/register-default-commands.js:575:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:12.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.9.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -0:11.3.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -0:10.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:10.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:10 core:paste (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:09.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -0:08.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:06.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:05.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:04.2.0 editor:move-line-up (atom-text-editor.editor.is-focused)
  2x -0:01.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-bootstrap4, v1.4.0
atom-ternjs, v0.13.2
autocomplete-paths, v1.0.2
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.1
esformatter, v1.22.0
file-icons, v1.6.16
icon-fonts, v2.0.3
language-fish-shell, v1.0.2
linter, v1.11.3
linter-sass-lint, v1.1.1
linter-xo, v0.12.0
minimap, v4.19.0
pigments, v0.24.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @joseluisq, it looks like you're still running v0.24.0 code, can you reproduce this error after a restart?

**Comment by joseluisq** [comment]
@abe33 I have updated Pigments to `v0.24.2` and this error hasn't reproduced again.
I will close this  issue for now :smile:
Thanks
