### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

### ISSUE THREAD

**Issue by skanne** [abe33/atom-pigments#155]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.24.2

### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:326

TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:326:28)
    at BackgroundRenderer.module.exports.RegionRenderer.createRegion (/Users/Sven/.atom/packages/pigments/lib/renderers/region-renderer.coffee:71:39)
    at BackgroundRenderer.module.exports.RegionRenderer.renderRegions (/Users/Sven/.atom/packages/pigments/lib/renderers/region-renderer.coffee:16:21)
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/Sven/.atom/packages/pigments/lib/renderers/background.coffee:11:16)
    at pigments-color-marker.ColorMarkerElement.render (/Users/Sven/.atom/packages/pigments/lib/color-marker-element.coffee:63:46)
    at /Users/Sven/.atom/packages/pigments/lib/color-buffer-element.coffee:246:47
    at Array.forEach (native)
    at /Users/Sven/.atom/packages/pigments/lib/color-buffer-element.coffee:246:20
```

### Commands

```
     -2:22 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -2:22 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -2:19.7.0 atom-alignment:alignMultiple (atom-text-editor.editor.is-focused)
     -2:05.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:04.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:03.7.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -2:01.8.0 find-and-replace:select-all (atom-text-editor.editor.is-focused)
  2x -1:34.6.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -1:32.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:31 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:30.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:30.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:29.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:27.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:25.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.5.0 pane-layout:square (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "packagesWithKeymapsDisabled": [
      "one-dark-ui"
    ],
    "projectHome": "/Users/Sven/Development/Web"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.28.24
build, v0.55.0
build-grunt, v0.4.0
build-gulp, v0.7.0
duplicate-line-or-selection, v0.5.0
editorconfig, v1.2.4
emmet, v2.4.1
file-icons, v1.6.16
language-jade, v0.6.3
minimap, v4.19.0
pane-layout-plus, v0.7.3
pigments, v0.24.2
project-manager, v2.7.6
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by abe33** [comment]
Are you still seeing this issue with the latest versions? To know whether I can close this issue or not?

**Comment by skanne** [comment]
If I knew how I provoked the error…

On 16 Mar 2016, at 16:32, Cédric Néhémie <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you still seeing this issue with the latest versions? To know whether I can close this issue or not?

**Comment by onetrev** [comment]
I still get this error. I believe it happens when I use Project Manager to switch projects in the same Atom window.

**Comment by geebru** [comment]
I'm having this happen within a Javascript file which has color declarations related to animations.

Having sections folded seems to increase the likelihood of the error occurring.

1. Make edits to JS file (doesn't matter if colors are involved are not).
2. Save the changes.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.38.0


### Stack Trace

Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:298

TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:298:28)
    at SquareDotRenderer.module.exports.DotRenderer.render (/Users/greg/.atom/packages/pigments/lib/renderers/dot.coffee:26:39)
    at SquareDotRenderer.module.exports.SquareDotRenderer.render (/Users/greg/.atom/packages/pigments/lib/renderers/square-dot.coffee:6:18)
    at pigments-color-marker.ColorMarkerElement.render (/Users/greg/.atom/packages/pigments/lib/color-marker-element.coffee:71:45)
    at /Users/greg/.atom/packages/pigments/lib/color-buffer-element.coffee:410:47
    at Array.forEach (native)
    at /Users/greg/.atom/packages/pigments/lib/color-buffer-element.coffee:410:20
```

### Commands

```
     -8:56.7.0 project-manager:list-projects (input.hidden-input)
     -8:52.7.0 core:confirm (input.hidden-input)
  5x -7:25.5.0 core:save (input.hidden-input)
  2x -1:13.9.0 core:backspace (input.hidden-input)
     -1:12.3.0 core:save (input.hidden-input)
     -0:02.0 core:delete (input.hidden-input)
     -0:01.3.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "cssnano",
      "welcome",
      "linter-stylelint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".sass-cache",
      "*.scssc",
      ".keep"
    ],
    "packagesWithKeymapsDisabled": [
      "linter"
    ],
    "projectHome": "/Users/greg/LookThink",
    "telemetryConsent": "limited",
    "useCustomTitleBar": true,
    "warnOnLargeFileLimit": 10
  },
  "pigments": {
    "autocompleteSuggestionsFromValue": true,
    "extendAutocompleteToColorValue": true,
    "markerType": "square-dot",
    "notifyReloads": false,
    "sassShadeAndTintImplementation": "bourbon",
    "sortPaletteColors": "by color",
    "traverseIntoSymlinkDirectories": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
busy, v0.7.0 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.8 (active)
git-plus, v7.0.7 (active)
linter, v1.11.21 (active)
linter-stylelint, v3.7.0 (inactive)
minimap, v4.26.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-pigments, v0.2.2 (active)
open-in-browser, v0.4.7 (inactive)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
svg-preview, v0.11.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
