### ISSUE TITLE
Cannot read property "id" of undefined

### ISSUE THREAD

**Issue by alice-em** [abe33/atom-pigments#179]
[Enter steps to reproduce below:]

1. View Grunt created css file (for SCSS compiling)
2. Immediate onslaught of error messages

It seems it happens whenever I switch to that particular tab.  Pigments works just fine on the source Sass file.

**Atom Version**: 1.9.0-dev-38ff433
**System**: Mac OS X 10.11.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.26.3

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:800

TypeError: Cannot read property 'id' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLineNumbersState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:800:56)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:488:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:127:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:662:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:336:29)
    at BackgroundRenderer.module.exports.RegionRenderer.createRegion (/Users/alice_em/.atom/packages/pigments/lib/renderers/region-renderer.coffee:78:39)
    at BackgroundRenderer.module.exports.RegionRenderer.renderRegions (/Users/alice_em/.atom/packages/pigments/lib/renderers/region-renderer.coffee:16:21)
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/alice_em/.atom/packages/pigments/lib/renderers/background.coffee:11:16)
    at pigments-color-marker.ColorMarkerElement.render (/Users/alice_em/.atom/packages/pigments/lib/color-marker-element.coffee:66:45)
    at pigments-color-marker.ColorMarkerElement.setModel (/Users/alice_em/.atom/packages/pigments/lib/color-marker-element.coffee:52:6)
    at pigments-markers.ColorBufferElement.requestMarkerView (/Users/alice_em/.atom/packages/pigments/lib/color-buffer-element.coffee:280:10)
    at pigments-markers.ColorBufferElement.updateMarkers (/Users/alice_em/.atom/packages/pigments/lib/color-buffer-element.coffee:263:8)
    at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/alice_em/.atom/packages/pigments/lib/color-buffer-element.coffee:140:6)
    at /Users/alice_em/.atom/packages/pigments/lib/color-buffer-element.coffee:72:52
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:335:22)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:329:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:278:26
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -4:45.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -4:44.8.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -4:33.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:21.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:20.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:18.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:28.9.0 core:copy (div.markdown-preview.native-key-bindings)
     -2:22.6.0 core:paste (atom-text-editor.editor.is-focused)
     -2:18.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:17.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:09.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:07.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:06.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:52 core:backspace (atom-text-editor.editor.is-focused)
     -1:49.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "git-plus",
      "merge-conflicts",
      "linter-js-standard",
      "color-picker",
      "emmet",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "jquery-snippets",
      "linter",
      "menu-manager",
      "react",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-python",
      "language-sql",
      "language-toml",
      "language-yaml",
      "language-objective-c",
      "language-perl",
      "webbox-color",
      "language-make",
      "activate-power-mode",
      "seti-icons"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "genesis-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2 (inactive)
afterlight, v1.0.0 (inactive)
an-old-hope-syntax, v0.5.0 (inactive)
angularjs, v0.3.4 (active)
apathy-theme, v1.10.4 (inactive)
atom-beautify, v0.29.7 (active)
atom-csscomb, v1.9.5 (inactive)
atom-formatter-jsbeautify, v1.1.2 (active)
atom-gooey-syntax, v0.2.1 (inactive)
atom-like-brackets-editor, v1.1.4 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.2.11 (inactive)
atomcasts-syntax, v0.10.3 (inactive)
autoclose-html, v0.23.0 (active)
autoprefixer, v3.2.0 (inactive)
burn, v0.2.1 (inactive)
cake-syntax, v0.5.0 (inactive)
color-picker, v2.1.1 (inactive)
colorblind-syntax, v1.1.2 (inactive)
earthsung-by-jackson-syntax, v0.3.0 (inactive)
eclectic-syntax, v0.2.1 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.11 (active)
firewatch-syntax, v1.0.1 (inactive)
fizzy, v0.16.0 (inactive)
flatland-dark, v0.1.6 (inactive)
flatland-dark-ui, v0.2.4 (inactive)
format-javascript-comment, v0.1.1 (inactive)
genesis-syntax, v1.0.7 (active)
git-plus, vundefined (inactive)
grandson-of-obsidian, v0.1.0 (inactive)
gruvbox-syntax, v2.3.1 (inactive)
hydra-syntax-theme, v1.3.0 (inactive)
idiomatic-dark-syntax, v0.1.3 (inactive)
imagemin, v1.0.0 (active)
isotope-ui, v2.7.1 (inactive)
jQuery, v1.2.4 (active)
language-SCSS, v0.4.0 (active)
lavender-syntax, v0.0.2 (inactive)
lavender-ui, v0.0.2 (inactive)
linter, v1.11.4 (inactive)
linter-csslint, v1.3.2 (active)
linter-js-standard, v3.3.2 (inactive)
linter-sass-lint, v1.4.3 (active)
linter-scss-lint, v3.0.4 (active)
magento-tools, v0.0.3 (inactive)
marronlatte-syntax, v0.1.1 (inactive)
material-design-syntax, v1.7.0 (inactive)
menu-manager, v0.5.0 (inactive)
merge-conflicts, v1.4.2 (inactive)
minimap, v4.23.5 (active)
monokai-soda, v0.5.0 (inactive)
native-ui, v0.18.2 (inactive)
neon-cursor, v1.4.0 (active)
neon-selection, v0.3.2 (active)
neon-syntax, v0.3.5 (inactive)
no-caffeine-syntax, v0.17.2 (inactive)
nucleus-dark-ui, v0.7.22 (inactive)
open-in-browser, v0.4.7 (inactive)
outlander-syntax, v1.1.0 (inactive)
php-cs-fixer, v2.5.6 (active)
pigments, v0.26.3 (active)
polaris-syntax, v0.1.0 (inactive)
pretty-dir, v0.0.17 (inactive)
rain-ui, v1.0.1 (inactive)
react, v0.15.0 (inactive)
redui-jm-syntax, v1.4.0 (inactive)
Sass-Syntax-Highlight, v0.1.1 (active)
seti-icons, v0.4.5 (inactive)
seti-ui, v1.1.2 (inactive)
seti-ui-red, v0.13.0 (inactive)
slack-ui, v0.7.0 (inactive)
slime, v1.6.1 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
steam-pirate-syntax, v0.3.0 (inactive)
tomorrow-night-eighties, v0.5.0 (inactive)
tomorrow-night-eighties-syntax, v0.13.0 (inactive)
unity-ui, v2.1.4 (inactive)
viriato, v0.12.0 (inactive)
webbox-color, v0.5.9 (inactive)
yoceanic-next-syntax, v0.5.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (active)
one-light-ui, v1.3.1 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.10.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.0.6 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.236.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.6 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.93.2 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.5 (inactive)
language-clojure, v0.20.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.18.0 (inactive)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.0 (inactive)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.2 (inactive)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.51.1 (active)
language-shellscript, v0.22.2 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.27.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.6 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by alice-em** [comment]
Related to an issue on Atom 1.9.0-dev https://github.com/atom/atom/issues/11745

**Comment by abe33** [comment]
Right, I was the one to report atom/atom#11745 ^^, it's now fixed on master 🎉
