### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by aditiapratama** [abe33/atom-pigments#183]
[Enter steps to reproduce below:]

1. Open xml file which contain color hex code
2. the error show up

**Atom Version**: 1.9.0-dev-97529f9
**System**: "Fedora release
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.26.3

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/local/share/atom/resources/app.asar/src/text-editor-presenter.js:800

TypeError: Cannot read property 'id' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLineNumbersState (/usr/local/share/atom/resources/app.asar/src/text-editor-presenter.js:800:56)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateTilesState (/usr/local/share/atom/resources/app.asar/src/text-editor-presenter.js:488:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/usr/local/share/atom/resources/app.asar/src/text-editor-presenter.js:127:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/usr/local/share/atom/resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.pixelPositionForScreenPosition (/usr/local/share/atom/resources/app.asar/src/text-editor-component.js:662:14)
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (/usr/local/share/atom/resources/app.asar/src/text-editor-element.js:336:29)
    at BackgroundRenderer.module.exports.RegionRenderer.createRegion (/home/aditia/.atom/packages/pigments/lib/renderers/region-renderer.coffee:78:39)
    at BackgroundRenderer.module.exports.RegionRenderer.renderRegions (/home/aditia/.atom/packages/pigments/lib/renderers/region-renderer.coffee:16:21)
    at BackgroundRenderer.module.exports.BackgroundRenderer.render (/home/aditia/.atom/packages/pigments/lib/renderers/background.coffee:11:16)
    at pigments-color-marker.ColorMarkerElement.render (/home/aditia/.atom/packages/pigments/lib/color-marker-element.coffee:66:45)
    at pigments-color-marker.ColorMarkerElement.setModel (/home/aditia/.atom/packages/pigments/lib/color-marker-element.coffee:52:6)
    at pigments-markers.ColorBufferElement.requestMarkerView (/home/aditia/.atom/packages/pigments/lib/color-buffer-element.coffee:280:10)
    at pigments-markers.ColorBufferElement.updateMarkers (/home/aditia/.atom/packages/pigments/lib/color-buffer-element.coffee:263:8)
    at pigments-markers.ColorBufferElement.editorConfigChanged (/home/aditia/.atom/packages/pigments/lib/color-buffer-element.coffee:140:6)
    at /home/aditia/.atom/packages/pigments/lib/color-buffer-element.coffee:72:52
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/usr/local/share/atom/resources/app.asar/src/tokenized-buffer.js:335:22)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/local/share/atom/resources/app.asar/src/tokenized-buffer.js:329:21)
    at /usr/local/share/atom/resources/app.asar/src/tokenized-buffer.js:278:26
    at /usr/local/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -1:15.5.0 tree-view:toggle (atom-text-editor.editor.vim-mode.normal-mode)
     -1:14.5.0 application:open-folder (atom-text-editor.editor.vim-mode.normal-mode)
     -0:38.6.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "w3c-validation",
      "aligner-php",
      "autocomplete-php",
      "git-history",
      "expose",
      "tree-view-git-branch"
    ],
    "projectHome": "/home/aditia/git",
    "themes": [
      "nucleus-dark-ui",
      "monokai"
    ]
  },
  "pigments": {
    "extendAutocompleteToColorValue": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
advanced-open-file, v0.16.2 (inactive)
aligner-php, v1.0.0 (inactive)
atom-beautify, v0.29.7 (inactive)
atom-css-unit-converter, v1.1.1 (inactive)
atom-dark-fusion-syntax, v1.1.0 (inactive)
atom-live-server, v1.2.5 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.2.11 (inactive)
atom-monokai, v0.10.2 (inactive)
atom-typescript, v8.10.1 (active)
autocomplete-emojis, v2.3.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-php, v0.3.7 (inactive)
cake-syntax, v0.5.0 (inactive)
color-picker, v2.1.1 (active)
duotone-dark-space-syntax, v1.0.0 (inactive)
duotone-dark-syntax, v1.0.0 (inactive)
duotone-light-syntax, v1.0.0 (inactive)
eclectic-syntax, v0.2.1 (inactive)
emmet, v2.4.3 (active)
expose, v0.11.1 (inactive)
file-icons, v1.7.11 (active)
firewatch-syntax, v1.0.1 (inactive)
fizzy, v0.16.0 (inactive)
font-viewer, v0.3.1 (active)
fonts, v1.2.0 (active)
genesis-ui, v0.5.0 (inactive)
git-blame, v0.4.8 (inactive)
git-control, v0.7.1 (inactive)
git-diff-details, v1.3.0 (active)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.13.4 (inactive)
git-projects, v1.17.0 (inactive)
git-time-machine, v1.5.2 (inactive)
gruvbox-syntax, v2.3.1 (inactive)
linter, v1.11.4 (active)
merge-conflicts, v1.4.2 (active)
minimap, v4.23.5 (active)
monokai, v0.18.0 (active)
monokai-seti, v0.7.0 (inactive)
multi-cursor, v2.1.3 (inactive)
native-ui, v0.18.2 (inactive)
neon-selection, v0.3.2 (active)
neutron-ui, v0.4.0 (inactive)
nucleus-dark-ui, v0.7.22 (active)
octocat-syntax, v0.1.5 (inactive)
open-in-browser, v0.4.7 (inactive)
open-terminal-here, v2.1.4 (inactive)
pigments, v0.26.3 (active)
predawn-syntax, v1.0.2 (inactive)
predawn-ui, v1.0.2 (inactive)
project-manager, v2.9.7 (active)
project-plus, v0.9.0 (active)
Remote-FTP, v0.8.3 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.1.2 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v0.8.1 (inactive)
state-of-nature-syntax, v0.1.0 (inactive)
Sublime-Style-Column-Selection, v1.5.1 (active)
svg-preview, v0.7.4 (active)
sync-settings, v0.7.2 (active)
tag, v0.4.0 (active)
tango-syntax, v0.4.1 (inactive)
tool-bar, v0.4.0 (active)
tool-bar-almighty, v0.6.1 (active)
tree-view-git-branch, v0.1.2 (inactive)
tree-view-git-status, v0.2.3 (active)
trendy-dark-syntax, v0.2.0 (inactive)
trendy-light-ui, v0.28.1 (inactive)
vim-mode, v0.65.0 (active)
w3c-validation, v0.4.0 (inactive)
wordpress-api, v1.2.2 (active)
yeti-syntax, v0.1.2 (inactive)
yeti-ui, v0.1.6 (inactive)
zip-folder, v3.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (inactive)
one-light-ui, v1.3.1 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.236.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.6 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.95.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.5 (active)
language-clojure, v0.20.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.18.0 (active)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.0 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.2 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.51.1 (active)
language-shellscript, v0.22.2 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.27.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.6 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by aditiapratama** [comment]
I think this has connection with this #179, but in my case it happen when I open xml file

**Comment by abe33** [comment]
Hi @aditiapratama, 

I already reported that in Atom (atom/atom#11745), it should be fixed by now.
