### ISSUE TITLE
I get some problem how can I do

### ISSUE THREAD

**Issue by chenshuxian** [abe33/atom-pigments#185]
nstalling “pigments@0.26.3” failed.Hide output…

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT, no such file or directory '/Users/jacky/.atom/packages/pigments/package.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:79:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:461:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

**Comment by abe33** [comment]
Hi @chenshuxian, have you tried reinstalling the package? Or removing the `/Users/jacky/.atom/packages/pigments` directory and installing again? Maybe something went wrong while copying the file on your disk.
