### ISSUE TITLE
Error when Deleting color variable

### ISSUE THREAD

**Issue by nickfmc** [abe33/atom-pigments#197]
[Enter steps to reproduce below:]

1. delete a color with a pigment swatch from your SCSS file
2. example element { color: $mycolor } error will be thrown as soon as you press backspace or del to remove the $mycolor
3. edit -- Also happens when color is not a variable and is in simple Hex format

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.29.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getStartScreenPosition' of undefined

```
At C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:833

TypeError: Cannot read property 'getStartScreenPosition' of undefined
    at pigments-markers.ColorBufferElement.updateDotDecorationsOffsets (file:///C:/Users/Nick/.atom/packages/pigments/lib/color-buffer-element.coffee:353:27)
    at file:///C:/Users/Nick/.atom/packages/pigments/lib/color-buffer-element.coffee:292:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:260:32
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:1231:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:1193:19)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\tokenized-buffer.js:409:27)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1328:26)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:2224:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.backspace (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:857:19)
    at TextEditor.object.(anonymous function) [as backspace] (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:backspace (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:414:21)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:655:34
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:1328:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:654:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Nick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:22.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:10.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:05.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:04.1.0 zentabs:pintab (div.title)
     -0:48 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:48 editor:newline (atom-text-editor.editor.is-focused)
     -0:47.6.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:45.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:27.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:04.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "sass-autocompile",
      "sync-settings"
    ],
    "themes": [
      "accents-ui",
      "code-macro"
    ]
  },
  "pigments": {
    "extendAutocompleteToColorValue": true,
    "extendAutocompleteToVariables": true,
    "markerType": "native-square-dot"
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0
atom-beautify, vundefined
autocomplete-sass, v0.1.0
clipboard-history, v0.6.6
code-macro, v0.1.0
color-picker, v2.1.1
compare-files, v0.6.2
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.13
flex-tool-bar, v0.10.0
less-than-slash, v0.13.0
linter, v1.11.4
linter-jshint, v2.1.0
linter-php, v1.2.0
pigments, v0.29.1
project-manager, v2.9.7
symbols-tree-view, v0.13.2
tool-bar, v0.4.0
wordpress-dictionary, v4.4.0
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by onetrev** [comment]
I get the same error, but it happens even if I am just deleting a hex colour value I believe.

**Comment by xekri** [comment]
+1.

**Comment by alanqthomas** [comment]
+1 . Unfortunately I had to disable pigments because of this issue. :(
