### ISSUE TITLE
Latest build not working

### ISSUE THREAD

**Issue by louisgv** [abe33/atom-pigments#198]
None of the color is being shown or highlighted on latest pigment.

pigments@0.29.2

Tested on 2 environments:

> atom-beta -v

```
Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

> atom -v

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

To those who have the same issue, downgrading to 0.28.4 works for me:

`apm-beta install pigments@0.28.4`

--- or --- 

`apm install pigments@0.28.4`

**Comment by kyleknighted** [comment]
I'm getting the same on Atom 1.8.0
It appears to work on occasion. It will randomly load up on some files, but then not on others. 
Will attempt to install previous Pigments version

**Comment by kyleknighted** [comment]
Looks like even with 0.28.4 pigments is still not loading properly.
![image](https://cloud.githubusercontent.com/assets/122591/16340419/b9071610-39ed-11e6-8095-e668d45757fc.png)

**Comment by C-Bouthoorn** [comment]
*irrelevant*: What font are you using @kyleknighted ? It looks nice

**Comment by kyleknighted** [comment]
@c-bouthoorn it's called Operator Mono from Typography.com

**Comment by abe33** [comment]
Hi there, sorry for the delay, I was off for a few days. 

Are you seeing any error messages in the devtools console? Also, What kind of pigments decorations are you using? Is it the same result with the `native-` equivalent?

**Comment by gabuuzz** [comment]
Hi, 
I'm getting the same error. (with native- too)

> $ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.9.0

```
Emitter is not a function TypeError: Emitter is not a function
    at new ExpressionsRegistry (/home/user/.atom/packages/pigments/lib/expressions-registry.coffee:21:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-expressions.coffee:24:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-expressions.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-scanner.coffee:2:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-scanner.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/tasks/scan-buffer-colors-handler.coffee:1:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/tasks/scan-buffer-colors-handler.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:52(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:686channel.onread @ internal/child_process.js:440
/usr/share/atom/resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:52(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:686channel.onread @ internal/child_process.js:440
/usr/share/atom/resources/app.asar/src/task.js:52 Emitter is not a function TypeError: Emitter is not a function
    at new ExpressionsRegistry (/home/user/.atom/packages/pigments/lib/expressions-registry.coffee:21:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-expressions.coffee:24:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-expressions.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-scanner.coffee:2:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/color-scanner.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/tasks/scan-buffer-colors-handler.coffee:1:16)
    at Object.<anonymous> (/home/user/.atom/packages/pigments/lib/tasks/scan-buffer-colors-handler.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:52(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:686channel.onread @ internal/child_process.js:440
/usr/share/atom/resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by abe33** [comment]
@gabuuzz What's your Atom version?

**Comment by gabuuzz** [comment]
@abe33 Version 1.8

**Comment by abe33** [comment]
Hmm, weird, the latest build on 1.8 is green on Travis (https://travis-ci.org/abe33/atom-pigments/jobs/140751423)

**Comment by adarrra** [comment]
hi, the same problem,
atom 1.8.0
downgrading to pigments@0.28.4 helps

**Comment by abe33** [comment]
Do you all get the same error message and stack as reported by @gabuuzz ?

**Comment by gabuuzz** [comment]
I've managed to fix the issue.

You need to modify ~/.atom/packages/pigments/lib/expressions-registry.coffee
Replace the first line by:
{Emitter} = require 'event-kit'

**Comment by abe33** [comment]
Hmm, the `Emitter` class is supposed to be available through `require 'atom'`, and I never had any issue to require atom from this file, but it's probably safer to not assume that this will always be the case.

**Comment by abe33** [comment]
I just published v0.31.1 which now includes `event-kit` as suggested by @gabuuzz, AFAICT it seems to fix that issue, let me know if you still get trouble.

**Comment by C-Bouthoorn** [comment]
As we are now a month later and it seems that it didn't occur again, I think this can be closed.

**Comment by abe33** [comment]
Closing it then.
