### ISSUE TITLE
Pigments throws error after update

### ISSUE THREAD

**Issue by thtliife** [abe33/atom-pigments#233]
This has happened for the last few updates.
Not a big issue, as a reload of atom has pigments working again.
Seems like the package is not testing for the pigments gutter before creating it, or not removing the gutter on deactivation, therefore throwing an error upon activation of the new gutter.

**Steps to reproduce**

1. Configure pigments to show colours in the editors gutter
2. Update pigments package
3. Error occurs upon activation of the new version of pigments

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.37.0

### Stack Trace

Failed to activate the pigments package

```
At Tried to create a gutter with a name that is already in use.

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2994:35)
    at pigments-markers.ColorBufferElement.initializeGutter (/Users/vito/.atom/packages/pigments/lib/color-buffer-element.coffee:276:23)
    at pigments-markers.ColorBufferElement.initializeNativeDecorations (/Users/vito/.atom/packages/pigments/lib/color-buffer-element.coffee:179:10)
    at /Users/vito/.atom/packages/pigments/lib/color-buffer-element.coffee:95:10
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at pigments-markers.ColorBufferElement.setModel (/Users/vito/.atom/packages/pigments/lib/color-buffer-element.coffee:88:36)
    at Object.module.exports.pigmentsViewProvider (/Users/vito/.atom/packages/pigments/lib/pigments.coffee:214:13)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:468:50)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:113:34)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at /Users/vito/.atom/packages/pigments/lib/color-project.coffee:370:40
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:332:9)
    at ColorProject.module.exports.ColorProject.initializeBuffers (/Users/vito/.atom/packages/pigments/lib/color-project.coffee:361:52)
    at new ColorProject (/Users/vito/.atom/packages/pigments/lib/color-project.coffee:170:12)
    at Function.module.exports.ColorProject.deserialize (/Users/vito/.atom/packages/pigments/lib/color-project.coffee:48:14)
    at Object.module.exports.activate (/Users/vito/.atom/packages/pigments/lib/pigments.coffee:19:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:397:31
```

### Commands

```
     -4:59.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -4:59.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:58.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:40.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:40.2.0 core:select-left (atom-text-editor.editor.is-focused)
  2x -4:16.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:09.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -3:55.7.0 core:copy (atom-text-editor.editor.is-focused)
     -3:53.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:19.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:41.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:40.5.0 core:undo (atom-text-editor.editor.is-focused)
     -1:21 core:paste (atom-text-editor.editor.is-focused)
     -1:19.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:15 core:save (atom-text-editor.editor.is-focused)
     -1:10.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-js-standard-jsx",
      "standard-formatter"
    ],
    "projectHome": "/Users/vito/work/projects",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "pigments": {
    "markerType": "gutter"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
color-picker, v2.2.2 (active)
comment-commander, v0.2.0 (inactive)
git-plus, v5.18.0 (active)
grammar-tab-colors, v0.2.0 (active)
highlight-selected, v0.11.2 (active)
indent-guide-improved, v1.4.10 (active)
language-babel, v2.42.3 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.18 (active)
linter-eslint, v7.3.2 (active)
linter-js-standard-jsx, v4.1.2 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-stylelint, v3.3.1 (active)
linter-tidy, v2.2.0 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
minimap-split-diff, v0.3.1 (active)
pigments, v0.37.0 (inactive)
servicenow-sync, v0.2.12 (active)
split-diff, v1.0.4 (inactive)
standard-formatter, v2.5.0 (inactive)
sublime-block-comment, v0.4.0 (active)
toggle-quotes, v1.0.0 (inactive)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment]
This is a recurring issue, not only with Pigments, but in Atom itself. Atom prevents some packages from destroying/reloading on update. Restarting Atom usually fixes it.
