### ISSUE TITLE
Pigments not showing up

### ISSUE THREAD

**Issue by guidolarosa** [abe33/atom-pigments#241]
Hi! This problem showed up after reinstalling Pigments on Atom via the Install Packages windows.
I reinstalled it because it wasn't working for a couple of days, and after I installed it for the second time, this error shows up...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.37.0

### Stack Trace

Uncaught TypeError: ColorContext is not a constructor

```
At /Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:240

TypeError: ColorContext is not a constructor
    at VariablesCollection.module.exports.VariablesCollection.getContext (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:240:9)
    at ColorProject.module.exports.ColorProject.getContext (/Users/GuidoLaRosa/.atom/packages/pigments/lib/color-project.coffee:425:29)
    at ColorProject.module.exports.ColorProject.findAllColors (/Users/GuidoLaRosa/.atom/packages/pigments/lib/color-project.coffee:246:17)
    at /Users/GuidoLaRosa/.atom/packages/pigments/lib/pigments.coffee:93:37
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:502:22)
    at Object.module.exports.findColors (/Users/GuidoLaRosa/.atom/packages/pigments/lib/pigments.coffee:238:20)
    at atom-workspace.atom.commands.add.pigments:find-colors (/Users/GuidoLaRosa/.atom/packages/pigments/lib/pigments.coffee:24:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:02.9.0 pigments:show-palette (atom-text-editor.editor)
     -6:20.7.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -6:13.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:29.9.0 command-palette:toggle (div.package-readme.native-key-bindings)
     -4:28.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:25.3.0 fuzzy-finder:toggle-file-finder (div.package-detail.panels-item)
  3x -2:53.7.0 core:backspace (atom-text-editor#pigments.extendedSearchNames.editor.mini.is-focused)
     -2:51.7.0 core:confirm (atom-text-editor#pigments.extendedSearchNames.editor.mini.is-focused)
     -0:21.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:18.7.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:12 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:07.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.3.0 pigments:find-colors (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jade"
    ],
    "ignoredNames": [
      "*.none"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "gaia-dark-syntax"
    ]
  },
  "pigments": {
    "delayBeforeScan": 200,
    "extendAutocompleteToColorValue": true,
    "extendedSearchNames": [
      "**/*.styl"
    ],
    "groupPaletteColors": "by file",
    "markerType": "background",
    "sortPaletteColors": "by color"
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-jade, v0.3.0 (active)
autoclose-html, v0.23.0 (active)
color-picker, v2.2.2 (active)
file-icons, v1.7.22 (active)
gaia-dark-syntax, v1.1.0 (active)
jade, v0.1.2 (inactive)
jade-beautify, v0.1.5 (active)
language-pug, v0.0.19 (active)
minimap, v4.25.0 (active)
monokai-complete-syntax, v0.2.3 (inactive)
pigments, v0.37.0 (active)
preview-plus, v1.2.7 (active)
processing-language, v0.2.0 (active)
seti-ui, v1.3.2 (inactive)
Stylus, v3.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

`

Is this a bug or a mistake in my configuration? 

Thanks.

**Comment by abe33** [comment]
Hi @guidolarosa, 

It's definitely a bug, but I hardly see how it could get to this point, it looks like either on file is missing (the color context one) or the module cache gets somehow corrupted.

Have you tried completely removing the package directory then reinstall it?

**Comment by guidolarosa** [comment]
Hi! I removed the package directory, I reinstalled it and now it shows me this error when I reload pigments via the Command Palette. I think it has something to do with the fact that Atom updated a couple days ago, but I'm not sure.

The following message is displayed by Atom:

`TypeError: ColorContext is not a constructor
    at VariablesCollection.module.exports.VariablesCollection.getContext (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:240:9)
    at VariablesCollection.module.exports.VariablesCollection.evaluateVariableColor (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:324:16)
    at VariablesCollection.module.exports.VariablesCollection.createVariable (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:315:6)
    at VariablesCollection.module.exports.VariablesCollection.add (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:173:10)
    at VariablesCollection.module.exports.VariablesCollection.addMany (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:179:14)
    at VariablesCollection.module.exports.VariablesCollection.updatePathCollection (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:144:16)
    at VariablesCollection.module.exports.VariablesCollection.updateCollection (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:111:40)
    at /Users/GuidoLaRosa/.atom/packages/pigments/lib/color-project.coffee:236:18`

Thanks for the response!

**Comment by Jeoxs** [comment]
Greetings, 

I have the same problem having this spec:

**Atom Version:** 1.11.2
**Electron Version:** 1.4.4-1
**System:** Arch Linux 64 bits
**Pigments Package:** v0.38.0

This bug didn't happen with Atom 1.7.3 and pigments v0.37.0. When installed, the pigments doesn't show on the Atom Package Menu.

**Comment by dodekeract** [comment]
Same issues here on macOS Sierra with atom 1.12.1.

**Comment by C-Bouthoorn** [comment]
I'm running Atom `1.13.0-beta1` with Pigments `0.38.0` on Linux 4.4.0 (Ubuntu 16.04), and I **don't** have this problem. Seems that an older version of Atom is the problem?

**Comment by guidolarosa** [comment]
@C-Bouthoorn I'll try installing the beta version of Atom and I come back to you.

**Comment by guidolarosa** [comment]
@C-Bouthoorn Hey! I tried running the Beta and it still doesn't work after reinstalling it. Atom displays the same issue "ColorContext is not a constructor". Could be a problem of my configuration?

Thanks.

**Comment by C-Bouthoorn** [comment]
It might be that something went wrong while installing pigments. Could you try re-installing (Also check the .apm for leftover pigments files)

**Comment by guidolarosa** [comment]
@C-Bouthoorn Yeah i tried installing it through the UI and with the console with apm, several times, but still doesn't work. Hope you can find a solution soon.

Bye!

**Comment by abe33** [comment]
@guidolarosa Have you tried installing version 0.37 from the console using `apm install pigments@0.37.0`?

**Comment by guidolarosa** [comment]
@abe33 well i tried it just now and still it doesn' work. I tried it on Atom Beta and Atom, none of them work. When I reload pigments it still shows this error message:

`
app/stylus/stylesheet.styl27:25
LF1 deprecationUTF-8Stylus+28
Pigments couldn't be reloaded
ColorContext is not a constructor
Hide Stack Trace
TypeError: ColorContext is not a constructor
    at VariablesCollection.module.exports.VariablesCollection.getContext (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:240:9)
    at VariablesCollection.module.exports.VariablesCollection.evaluateVariableColor (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:324:16)
    at VariablesCollection.module.exports.VariablesCollection.createVariable (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:315:6)
    at VariablesCollection.module.exports.VariablesCollection.add (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:173:10)
    at VariablesCollection.module.exports.VariablesCollection.addMany (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:179:14)
    at VariablesCollection.module.exports.VariablesCollection.updatePathCollection (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:144:16)
    at VariablesCollection.module.exports.VariablesCollection.updateCollection (/Users/GuidoLaRosa/.atom/packages/pigments/lib/variables-collection.coffee:111:40)
    at /Users/GuidoLaRosa/.atom/packages/pigments/lib/color-project.coffee:236:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by abe33** [comment]
@guidolarosa Actually you still have v0.38 installed, you might probably need to `apm uninstall pigments` then `apm install pigments@0.37.0`

**Comment by guidolarosa** [comment]
Hey @abe33 ! Yes but I installed 0.37.0 throught apm and Atom. Didn't work either...
