### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by forestgagnon** [abe33/atom-pigments#264]
This happens every time I open a .md file

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.38.0

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Users/fgagno/.atom/packages/pigments/lib/color-buffer-element.coffee:303

TypeError: Cannot read property 'row' of undefined
    at /Users/fgagno/.atom/packages/pigments/lib/color-buffer-element.coffee:303:53
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:547:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayLayer.module.exports.DisplayLayer.reset (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:225:20)
    at TextEditor.module.exports.TextEditor.update (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:453:27)
    at TextEditor.module.exports.TextEditor.setWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3425:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateClientWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:911:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollbarDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:986:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateHorizontalDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:880:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:136:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:202:38)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:303:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:993:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:437:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:545:18
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

### Commands

```
     -0:03.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:00.4.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-markdown",
      "metrics",
      "exception-reporting",
      "linter-sass-lint",
      "activate-power-mode",
      "welcome",
      "background-tips",
      "minimap-bookmarks",
      "linter-clang",
      "linter-eslint"
    ],
    "packagesWithKeymapsDisabled": [
      "sort-lines"
    ],
    "telemetryConsent": "no",
    "themes": [
      "seti-ui",
      "atom-material-syntax-dark"
    ]
  },
  "pigments": {
    "extendAutocompleteToColorValue": true,
    "groupPaletteColors": "by file",
    "markerType": "native-dot",
    "sortPaletteColors": "by name"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (inactive)
atom-beautify, v0.29.16 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.8 (inactive)
atom-reverser, v2.4.0 (inactive)
atom-ternjs, v0.16.1 (active)
atomic-chrome, v0.3.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-webgl, v1.1.0 (active)
behave-theme, v1.6.0 (inactive)
blame, v0.10.2 (active)
change-case, v0.6.3 (active)
character-table, v0.4.3 (active)
charcode-display, v0.2.1 (active)
color-picker, v2.2.3 (active)
custom-title, v1.0.1 (active)
docblockr, v0.9.1 (active)
expand-selection-to-quotes, v0.11.0 (inactive)
file-icons, v2.0.8 (active)
filesize, v2.0.2 (active)
flex-tool-bar, v0.11.0 (active)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (inactive)
git-plus, v7.0.7 (active)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.39 (active)
indent-guide-improved, v1.4.12 (active)
js-hyperclick, v1.10.1 (active)
jumpy, v3.1.3 (inactive)
language-latex, v1.0.0 (active)
linter, v1.11.21 (active)
linter-clang, v3.4.4 (inactive)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (inactive)
linter-jsonlint, v1.3.0 (active)
linter-markdown, v3.0.2 (inactive)
linter-sass-lint, v1.7.4 (inactive)
markdown-pdf, v1.5.0 (inactive)
maximize-panes, v0.2.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.26.5 (active)
minimap-bookmarks, v0.4.2 (inactive)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.2 (active)
node-debugger, v1.9.2 (active)
one-dark-material-syntax, v1.0.2 (inactive)
package-sync, v1.1.0 (active)
pdf-view, v0.54.0 (active)
pigments, v0.38.0 (active)
react, v0.16.2 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (active)
sort-lines, v0.14.0 (inactive)
todo-show, v1.9.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (active)
trailing-semicolon, v1.1.0 (inactive)
windows-carriage-return-remover, v0.1.3 (inactive)
wordcount, v2.10.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Osuriel** [comment]
I have the same Error popping up. how do i fix it? its gettign really annoying..

**Comment by Richie2** [comment]
I have the same issue opening or creating a any file type.
Tried reinstalling the plugin but still have the sames issues. 

[Enter steps to reproduce below:]

1. open html file

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.38.0


### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Users/Richard/.atom/packages/pigments/lib/color-buffer-element.coffee:303

TypeError: Cannot read property 'row' of undefined
    at /Users/Richard/.atom/packages/pigments/lib/color-buffer-element.coffee:303:53
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:547:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayLayer.module.exports.DisplayLayer.reset (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:225:20)
    at TextEditor.module.exports.TextEditor.update (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:453:27)
    at TextEditor.module.exports.TextEditor.setWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3425:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateClientWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:911:20)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollbarDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:986:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateHorizontalDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:880:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:136:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:202:38)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:303:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:993:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:288:22)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:500:14)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:434:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:545:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs",
      "git-plus"
    ],
    "projectHome": "/Users/Richard/sites",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ]
  },
  "pigments": {
    "markerType": "native-dot"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.16.1 (inactive)
cobalt2-syntax, v0.5.0 (active)
file-icons, v2.0.8 (active)
git-plus, v7.0.7 (inactive)
linter, v1.11.21 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v8.0.0 (active)
markdown-writer, v2.6.3 (inactive)
pigments, v0.38.0 (active)
react, v0.16.2 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by DeanmvSG** [comment]
I've just had this as well.  Are you using the "native-dot" issue under "Marker Type"?  I was on "native-background" and this issue never appears, switching to "native-dot" makes it appear on every file open, whereas switching to just "dot" seemed to stop the issue from appearing for me.

**Comment by forestgagnon** [comment]
That did indeed fix the issue for me temporarily.

**Comment by Richie2** [comment]
The same here, the issue seems to be with native dot.

**Comment by C-Bouthoorn** [comment]
The matching (3rd party) packages seem to be:

```
file-icons, v2.0.8
linter, v1.11.21
linter-csslint, v1.3.3
pigments, v0.38.0
```

Trying to change Marker Type to `native-dot` raises the issue for me too, and I'm only having `linter` and `pigments` enabled out of those.

### System
```
$ node -v
v6.9.4

$ npm -v
4.1.1

$ apm -v
apm  1.1.1
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2

$ atom-beta -v
Atom    : 1.14.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ uname -srvpo
Linux 4.4.0-32-generic #51-Ubuntu SMP Tue Jul 19 18:09:07 UTC 2016 x86_64 GNU/Linux
```

I'll try to get more information. I'll update this answer if I find more

**Comment by artemsheludko** [comment]
A similar error when selecting "native-dot" and "native-square-dot". With other settings, there are no errors :smiley:

**Comment by C-Bouthoorn** [comment]
@artemsheludko That is probably because this issue was raised when the marker-type was one of *-dot. Nice catch though!

**Comment by jurc192** [comment]
I have the same problem. Error (same as upper (first) post) pops up when opening .md files.

**Comment by thierryc** [comment]
I have the same 
Error (same as upper (first) post) pops up when opening .md files.



$ node -v
v6.9.2

$ npm -v
3.10.9

$ apm -v
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1

**Comment by artemsheludko** [comment]
Interestingly, error occurs when you open any file, if you set in the settings of "Soft wrap"

**Comment by randohinn** [comment]
Why is this still not fixed?

**Comment by ryanaltvater** [comment]
Not only do I get the error on startup or opening a file, but I also get the error popup every time I resize the Atom window lol...? Explain that one. (shrugs)
