### ISSUE TITLE
Uncaught TypeError: Cannot read property 'color' of null

### ISSUE THREAD

**Issue by Mooreplusone** [abe33/atom-pigments#27]
[Enter steps to reproduce below:]

1. ... Navigated to folder and dragged the icon onto the ATOM app in dock bar
2. ... App started and error appeared. 

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.4.5

### Stack Trace

Uncaught TypeError: Cannot read property 'color' of null

```
At /Users/jasonmoore/.atom/packages/pigments/lib/renderers/background.coffee:8

TypeError: Cannot read property 'color' of null
  at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/jasonmoore/.atom/packages/pigments/lib/renderers/background.coffee:8:24)
  at pigments-color-marker.ColorMarkerElement.render (/Users/jasonmoore/.atom/packages/pigments/lib/color-marker-element.coffee:46:46)
  at /Users/jasonmoore/.atom/packages/pigments/lib/color-buffer-element.coffee:93:45
  at Array.forEach (native)
  at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/jasonmoore/.atom/packages/pigments/lib/color-buffer-element.coffee:93:18)
  at /Users/jasonmoore/.atom/packages/pigments/lib/color-buffer-element.coffee:62:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:334:22)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:325:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26

```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "themes": [
      "atom-dark-ui",
      "monokai-soda"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.17.1
color-picker, v2.0.4
linter, v0.12.7
minimap, v4.9.4
monokai-soda, v0.5.0
pigments, v0.4.5
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Not sure why you get that error, is it systematic when you open that project?

**Comment by oskarkrawczyk** [comment]
I can confirm this error:

Stack trace:

```
TypeError: Cannot read property 'color' of null
  at BackgroundRenderer.module.exports.BackgroundRenderer.render (/Users/oskar/.atom/packages/pigments/lib/renderers/background.coffee:8:24)
  at pigments-color-marker.ColorMarkerElement.render (/Users/oskar/.atom/packages/pigments/lib/color-marker-element.coffee:47:46)
  at /Users/oskar/.atom/packages/pigments/lib/color-buffer-element.coffee:95:45
  at Array.forEach (native)
  at pigments-markers.ColorBufferElement.editorConfigChanged (/Users/oskar/.atom/packages/pigments/lib/color-buffer-element.coffee:95:18)
  at /Users/oskar/.atom/packages/pigments/lib/color-buffer-element.coffee:62:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:334:22)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:325:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
```

**Atom Version**: 1.0.1-77d7e7a (1.0.1-77d7e7a)
**System**: Mac OS X 10.10.4
**Thrown From**: pigments, v0.8.1

**Comment by walles** [comment]
@abe33, what have you managed to learn from the stack trace attached to this ticket?

  Regards /Johan

**Comment by abe33** [comment]
Not so much actually, I lack some reproduction steps to fully understand the root cause of this problem. I can patch the renderer to make sure to never access an undefined color though and remove the symptoms. 
But if somebody can isolate the conditions that trigger that bug I could fix the cause and not just the symptom.

**Comment by abe33** [comment]
I've put some warning in the situation that was previously failing instead of letting the error uncatched, I'll be interested to see what appears in the logs if you encounter it again.
