### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by OussamaRomdhane** [abe33/atom-pigments#279]
1. Open the palette view
2. Restart Atom

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/oussama/.atom/packages/pigments/lib/palette-element.coffee:95

TypeError: Cannot read property 'dispose' of undefined
    at /packages/pigments/lib/palette-element.coffee:95:19)
    at /packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:15:57)
    at /app.asar/src/pane-container-element.js:38:13)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/app.asar/src/pane-container.js:163:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/app.asar/src/pane-container.js:173:19)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:919:21)
    at Pane.module.exports.Pane.splitRight (/app.asar/src/pane.js:899:19)
    at Pane.module.exports.Pane.findOrCreateRightmostSibling (/app.asar/src/pane.js:971:21)
    at /app.asar/src/workspace.js:426:43)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:434:12)
    at WelcomePackage.show (/app.asar/node_modules/welcome/lib/welcome-package.js:79:95)
    at /app.asar/node_modules/welcome/lib/welcome-package.js:72:20)
    at next (<anonymous>)
    at step (/app.asar/node_modules/welcome/lib/welcome-package.js:11:273)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
git-plus 7.2.2 
linter 1.11.21 
linter-jshint 3.0.2 
minimap 4.26.8 
open-recent 5.0.0 
pigments 0.39.0 
todo-show 1.9.0 
```

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
