### ISSUE TITLE
TypeError handler.bind is not a function

### ISSUE THREAD

**Issue by Ben3eeE** [abe33/atom-pigments#287]
**Steps to Reproduce:**

1. Disable all packages except pigments
1. Restart Atom
1. Drag a `css` file from the Windows file explorer to Atom

**Expected:** No Error in console
**Actual:** Error in console as pic below shows

![image](https://cloud.githubusercontent.com/assets/1058982/24153978/34054af8-0e50-11e7-96da-5a486d9e0d91.png)

```
pigments@0.39.1

Atom    : 1.16.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 7 64-bit
```

**Comment by C-Bouthoorn** [comment]
For reference:

```
handler.bind is not a function TypeError: handler.bind is not a function	(C:\Users\xxx\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\src\task.js:52)
	at process.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\src\task-bootstrap.js:82:24)
	at emitTwo (events.js:106:13)
	at process.emit (events.js:191:7)
	at process.nextTick (internal/child_process.js:744:12)
	at _combinedTickCallback (internal/process/next_tick.js:67:7)
	at process._tickCallback (internal/process/next_tick.js:98:9)
```

@Ben3eeE  could you copy/paste the error message instead of making a screenshot next time? :smile: That makes it easier for us to debug

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
