### ISSUE TITLE
Failed to initialize the pigments package

### ISSUE THREAD

**Issue by jtwalters25** [abe33/atom-pigments#288]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to initialize the pigments package

```
At Cannot read property 'initialize' of null

TypeError: Cannot read property 'initialize' of null
    at /app.asar/src/package.js:163:49
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.initializeIfNeeded (/app.asar/src/package.js:156:12)
    at Object.createView (/app.asar/src/package.js:542:21)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:111:34)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at ColorProject.module.exports.ColorProject.updateColorBuffers (/packages/pigments/lib/color-project.coffee:317:40)
    at /packages/pigments/lib/color-project.coffee:71:8
    at Config.module.exports.Config.observeKeyPath (/app.asar/src/config.js:616:7)
    at Config.module.exports.Config.observe (/app.asar/src/config.js:141:21)
    at /packages/pigments/lib/color-project.coffee:70:36)
    at Object.activate (/packages/pigments/lib/pigments.coffee:21:11)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -8:15.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -8:15.2.0 editor:newline (input.hidden-input)
     -8:14.6.0 core:paste (input.hidden-input)
     -6:58.8.0 core:save (input.hidden-input)
     -5:59.7.0 core:move-right (input.hidden-input)
  4x -5:59.4.0 core:backspace (input.hidden-input)
     -5:57.4.0 core:save (input.hidden-input)
     -4:56.6.0 core:cut (input.hidden-input)
  5x -4:55.6.0 core:backspace (input.hidden-input)
     -4:51.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:51.6.0 editor:newline (input.hidden-input)
     -4:51.2.0 core:paste (input.hidden-input)
     -4:48.8.0 core:save (input.hidden-input)
     -4:43.8.0 intentions:highlight (input.hidden-input)
     -4:22 platformio-ide-terminal:toggle (input.hidden-input)
     -1:12.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-clock 0.1.6 
atom-html-preview 0.1.22 
Atom-Syntax-highlighting-for-Sass 0.5.0 
atom-terminal 0.8.0 
atom-typescript 11.0.1 
auto-detect-indentation 1.3.0 
auto-encoding 0.6.3 
auto-header 0.2.4 
auto-id-class 0.2.6 
auto-indent 0.5.0 
auto-require-tags 0.0.5 
auto-run 0.2.1 
auto-semicolon 1.1.0 
autoupdate-packages 1.3.1 
busy-signal 1.3.0 
color-picker 2.2.5 
csscomb 0.3.1 
csslint 1.1.5 
emmet 2.4.3 
file-icons 2.0.17 
intentions 1.1.2 
linter 2.1.0 
linter-eslint 8.1.4 
linter-jsonlint 1.3.0 
linter-ui-default 1.2.1 
linter-write-good 0.8.0 
minimap 4.26.8 
open-in-browser 0.4.7 
photon-syntax 0.9.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
qolor 0.4.1 
scope-inspector 1.0.1 
toggle-packages 1.1.0 
tree-view-git-status 1.3.1 
```

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
