### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelPositionForScreenPosition' of null

### ISSUE THREAD

**Issue by doar2016** [abe33/atom-pigments#289]
Getting this error when using Project Manager to switch between projects in the same window.

Here's the Stack Trace:

```
TypeError: Cannot read property 'pixelPositionForScreenPosition' of null
    at atom-text-editor.TextEditorElement.pixelPositionForScreenPosition (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor-element.js:304:28)
    at pigments-markers.<anonymous> (file:///C:/Users/xxxxxx/.atom/packages/pigments/lib/color-buffer-element.coffee:378:36)
    at pigments-markers.ColorBufferElement.updateDotDecorationsOffsets (file:///C:/Users/xxxxxx/.atom/packages/pigments/lib/color-buffer-element.coffee:370:7)
    at file:///C:/Users/xxxxxx/.atom/packages/pigments/lib/color-buffer-element.coffee:304:14
    at Array.forEach (native)
    at file:///C:/Users/xxxxxx/.atom/packages/pigments/lib/color-buffer-element.coffee:303:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\src\text-editor.js:550:32
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at DisplayLayer.emitDidChangeSyncEvent (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:755:18)
    at decorationLayerDisposable.textDecorationLayer.onDidInvalidateRange (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:154:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\src\tokenized-buffer.js:220:22)
    at C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\src\tokenized-buffer.js:185:26
    at C:\Users\xxxxxx\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\underscore\underscore.js:666:47
```

**Comment by C-Bouthoorn** [comment]
Closing because I think the problem didn't persist. Let me know if it does.
