### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by eadwu** [abe33/atom-pigments#295]
### Versions
Atom `1.16.0-beta0 x64`
Pigments version `0.39.1`
Arch Linux ( DE: `xfce4`, WM: `i3-gaps` )

### How to reproduce
1. Start Atom
2. View
3. Developer
4. Toggle Developer Tools

### Stack trace
```
Invalid regular expression: /var(--indeterminate))(?![-_])/: Unmatched ')' SyntaxError: Invalid regular expression: /var(--indeterminate))(?![-_])/: Unmatched ')'
    at RegExp (native)
    at Object.appendResult ($HOME/.atom/packages/pigments/lib/variable-expression.coffee:38:18)
    at VariableExpression.handle (evalmachine.<anonymous>:2:12)
    at VariableExpression.module.exports.VariableExpression.parse ($HOME/.atom/packages/pigments/lib/variable-expression.coffee:44:8)
    at VariableParser.module.exports.VariableParser.parse ($HOME/.atom/packages/pigments/lib/variable-parser.coffee:7:16)
    at VariableScanner.module.exports.VariableScanner.search ($HOME/.atom/packages/pigments/lib/variable-scanner.coffee:27:24)
    at ReadStream.<anonymous> ($HOME/.atom/packages/pigments/lib/tasks/scan-paths-handler.coffee:26:31)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1994:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)(anonymous function) @ /usr/share/atom-beta/resources/app.asar/src/task.js:52
```

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
