### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Parsoa** [abe33/atom-pigments#313]
I've been getting this issue constantly the past few weeks. Seems not to be caused by another theme or plugin I have installed as I tried disabling them. Here is the stack trace:

```
TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:305:23)
    at Module._resolveFilename (module.js:446:31)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at requireCore (/Users/Parsoa/.atom/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/Users/Parsoa/.atom/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/Users/Parsoa/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:374:1
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:1
```

**Comment by JianmingXia** [comment]
i have same problem

**Comment by crigger** [comment]
Samesys

**Comment by clyzhao** [comment]
me too. How can fix this?

**Comment by disresz** [comment]
Same problem here

**Comment by abe33** [comment]
Hi here, are you all running beta? or stable?

**Comment by Tachibana446** [comment]
same problem
version 1.18.0 ia32 (windows) (automatically update)
thank you,
