### ISSUE TITLE
Failed to activate the pigments package

### ISSUE THREAD

**Issue by visormatt** [abe33/atom-pigments#314]
The following startup error occurs on **_Atom 1.19.0-beta0_**. 
```
Failed to activate the pigments package.
Cannot find 'highlights-component' in the require cache .
```

**Stack Trace:**
```
Cannot find 'highlights-component' in the require cache.
Hide Stack Trace
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/Users/some-user/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
```

**General Question:**
Is there also a bug to be created in the sense that this is a new issue and not the same as the [2016 bug here](https://github.com/abe33/atom-pigments/issues/201)? It would be amazing to be able to say `nope, this is indeed a new issue`.

**Comment by jackplug** [comment]
Me too:

```
**Atom**: 1.19.0-beta0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1
```

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0-beta0/resources/app/src/atom-environment.js:843:36
```

**Comment by Greenek** [comment]
`highlights-component` has been removed from atom. More details: https://github.com/atom/atom/pull/13880

**Comment by borishere** [comment]
No one is going to fix it? :|

**Comment by miclaus** [comment]
+1

**Comment by ChildishGiant** [comment]
Is there a temp alternative or is this a dead repo?

**Comment by JianmingXia** [comment]
how can fix this error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.0


### Stack Trace

Failed to activate the pigments package

```
At Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:305:23)
    at Module._resolveFilename (module.js:446:31)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at requireCore (/packages/atom-pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/packages/atom-pigments/lib/pigments.coffee:297:26)
    at Object.activate (/packages/atom-pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:832:1
```

**Comment by optikfluffel** [comment]
@borishere @ChildishGiant Why don't _you_ fix it, when you're that impatient? I'm pretty sure PRs are welcome.
@JianmingXia I think you have the problem of #313, not the one from this issue here.

**Comment by beamaster** [comment]
cd /Users/name/.atom/pakages/your issue pakage
npm install pakagename

restart atom

**Comment by borishere** [comment]
@optikfluffel I have too much work my friend.

**Comment by jackplug** [comment]
@beamaster I'm sure that's well-intended (update the package directly, right?) but it does not help, unfortunately - @abe33 probably has the same problem as @borishere (like many of us :))

**Comment by plessbd** [comment]
@borishere @ChildishGiant your using a beta version of atom dont expect everything to work.  THe maintainer will get to this when they have the time I am sure.

**Comment by borishere** [comment]
@plessbd you are right if it works on a stable version :)

**Comment by beamaster** [comment]
@jackplug  that's bad news ,  you could have a try to unload the ATOM and install it again.you must backup your plugins installed already. good luck to u

**Comment by thompsonemerson** [comment]
:(

**Comment by kaela** [comment]
Upgrading to 0.39.1 fixed the issue for me.

**Comment by gtramontina** [comment]
Would simply adding `highlights-component` to this package's dependencies fix this problem? Or is it not the right way of dealing with atom packages? (honest question, as I'm used to regular node packages, but have never dealt with an atom plugin myself). If so, I can just go ahead and submit a PR…

**Comment by Rapidisimo** [comment]
Hi everyone.
I just went to Atom>Preferences>Updates>Check for Updates
and proceeded to update all my packages.

This fixed it.

**Comment by Greenek** [comment]
## **`highlights-component` was internal, undocumented class in Atom core, not separate package!**

It has been removed in `1.19.0-beta.1` as a result of new layout rendering code https://github.com/atom/atom/pull/13880

If you really need this plugin, go back to `1.18.0` and wait for updates.

**Comment by GeorgeWL** [comment]
Wondering, are you aware of a quick temporary hotfix that I can apply locally?

Cause some of the new beta features I've really fell in love with.

**Comment by iCodeWithYou** [comment]
When you uninstall and reinstall atom it allows you to upload those packages which fix this issue.

**Comment by GeorgeWL** [comment]
@iCodeWithYou you talking about the beta or the main?

**Comment by mbokil** [comment]
Uninstall/reinstall of Atom only works with version 1.18 the stable build to obtain missing packages. Highlights-component was removed rom Atom 1.19 beta and the plugin will need to be refactored before it will work. Use Atom 1.18 until Pigments has been updated.

**Comment by GeorgeWL** [comment]
Wondering, are you aware of a quick temporary hotfix that I can apply locally?

Cause some of the new beta features I've really fell in love with.

**Comment by C-Bouthoorn** [comment]
@GeorgeWL Atom's rendering system has changed, so the old package isn't compatible anymore. It's possible a full rewrite would be necessary to have a "quick hotfix". I suppose going back to Atom stable is the quickest fix you can do.

**Comment by rafaelgaspar** [comment]
GitHub did a nice article about this changes, if you don't understand what is happening on 1.19 you should probably read this instead of trying to find hotfix. The article even mentions pigments.

http://blog.atom.io/2017/06/22/a-new-approach-to-text-rendering.html

**Comment by Greenek** [comment]
I made simple support for new Atom renderer. 

PR: https://github.com/abe33/atom-pigments/issues/319

![zrzut ekranu 2017-07-25 o 03 16 48](https://user-images.githubusercontent.com/160300/28551525-ccdd8be6-70e8-11e7-865e-0492c136a546.png)

**Comment by maksim-litvinov** [comment]
Works in 0.40 pigments with atom-beta-5

**Comment by enoversum** [comment]
@Greenek As soon as I choose another way of displaying the colour in settings, pigments fails again. Since I changed the settings, I cannot change it back anymore. Just so you know ;) .

**Comment by visormatt** [comment]
This appears to be resolved in the newest Beta `1.19.0-beta5 x64`. Going to close this out now, much ❤️ to Atom and all the folks building it!!! 

![GitHub Logo](https://media.giphy.com/media/13twUEuUnCrEju/giphy.gif)

**Comment by numez** [comment]
Fixed updating "pigments" package from atom packages update center

**Comment by lilankaravinath** [comment]
**It can be simply fixed when you update pigment package.**
File -> Setting -> Updates -> Update pigment package (in my case I updated it to 0.40.2)

**Comment by Greenek** [comment]
Maybe it's because the bug has been fixed in July… 

**Please!** Next time, take a minute and read at least the last few comments, maybe there is no need to notify all participants (20 users in this case), that you found a solution for the fixed problem everyone already forgot about.
