### ISSUE TITLE
Uncaught TypeError: Cannot read property 'colorMarkerForMouseEvent' of undefined

### ISSUE THREAD

**Issue by tsl0922** [abe33/atom-pigments#32]
[Enter steps to reproduce below:]

1. goto any package's settings page
2. right click on any text input

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.7.2

### Stack Trace

Uncaught TypeError: Cannot read property 'colorMarkerForMouseEvent' of undefined

```
At /Users/tsl0922/.atom/packages/pigments/lib/pigments.coffee:154

TypeError: Cannot read property 'colorMarkerForMouseEvent' of undefined
  at Object.module.exports.colorMarkerForMouseEvent (/Users/tsl0922/.atom/packages/pigments/lib/pigments.coffee:154:16)
  at Object.module.exports.shouldDisplayContextMenu (/Users/tsl0922/.atom/packages/pigments/lib/pigments.coffee:149:5)
  at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/Users/tsl0922/.atom/packages/pigments/lib/pigments.coffee:132:36)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:108:25)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:166:27)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -3:31.6.0 core:copy (ol.native-key-bindings.breadcrumb)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "linter-htmlhint",
      "minimap",
      "merge-conflicts",
      "vim-mode",
      "emmet",
      "regex-railroad-diagram",
      "linter-scss-lint"
    ],
    "projectHome": "/Users/tsl0922/workspace",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "pigments": {
    "markerType": "dot"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
autoclose-html, v0.18.0
editorconfig, v1.0.0
file-icons, v1.5.7
hex, v0.6.2
language-apache, v1.3.0
language-docker, v1.1.3
language-haml, v0.21.0
language-lua, v0.9.3
language-nginx, v0.5.3
language-scala, v1.1.3
language-viml, v0.2.0
language-yaml, v0.22.0
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
pigments, v0.7.2
pretty-json, v0.3.3
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report :bow:, I should have anticipated this case, I'll patch this soon.
