### ISSUE TITLE
Failed to activate the pigments package

### ISSUE THREAD

**Issue by jonhyleo** [abe33/atom-pigments#328]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:27.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-less 0.1.10 
atom-live-server 2.1.2 
atom-minify 0.8.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autoupdate-packages 1.3.1 
browser-plus 0.0.98 
build 0.68.0 
build-gulp 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
chester-syntax 0.4.0 
csslint 1.1.5 
dracula-syntax 2.0.5 
emmet 2.4.3 
file-icons 2.1.10 
fonts 3.0.2 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
less-autocompile 1.0.0 
linter 2.2.0 
linter-bootlint 1.0.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
linter-write-good 0.9.0 
minimap 4.29.3 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
monokai-seti 0.9.0 
open-in-browsers 0.0.30 
open-recent 5.0.0 
php-cs-fixer 4.1.0 
pigments 0.39.1 
project-manager 3.3.5 
sass-autocompile 0.13.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sync-settings 0.8.2 
todo-show 1.11.0 
```

**Comment by vicner** [comment]
Same here. After updating to Atom 1.18.0 x64, 

Seeing the bug:
Failed to activate the pigments package
Cannot read property 'length' of undefined
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:305:23)
    at Module._resolveFilename (module.js:446:31)
    at Module._resolveFilename (/Users/billy/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Users/billy/Downloads/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at requireCore (/Users/billy/.atom/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/Users/billy/.atom/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/Users/billy/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Users/billy/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Users/billy/Downloads/Atom.app/Contents/Resources/app/src/atom-environment.js:846:34
The error was thrown from the pigments package. This issue has already been reported.
View Issue

**Comment by cjmosure** [comment]
Once you update atom, check updates again and there should be an update for the atom-pigments that fixes the issue

**Comment by ryanlloydfrench** [comment]
Can confirm that the update to the package fixes this issue.

**Comment by Arima-P** [comment]
Cannot find 'highlights-component' in the require cache.
Hide Stack Trace
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (file:///C:/Users/pigle/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (file:///C:/Users/pigle/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (file:///C:/Users/pigle/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package.js:253:25)
    at C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package.js:99:21)
    at C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package-manager.js:645:40)
    at C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\package-manager.js:603:52)
    at C:\Users\pigle\AppData\Local\atom\app-1.19.0\resources\app\src\atom-environment.js:843:36

**Comment by tayfunyasar** [comment]
updating plugins solved my issue.

**Comment by C-Bouthoorn** [comment]
Same issue here: https://github.com/abe33/atom-pigments/issues/314

**Comment by iDevSpread** [comment]
Hi, I met the same issue. I found the solution to this issue is to update the corresponding package. After finishing the updates, all compling errors are gone.

**Comment by vicner** [comment]
Thanks, updating plugin solved my issue.

**Comment by jonhyleo** [comment]
Updating plugin solved the issue. Thanks!

**Comment by achentha** [comment]
@cjmosure 

thanks, updating the package did fix the problem.

**Comment by yaser-alazem** [comment]
Worked perfectly after plugin update .

**Comment by Awram** [comment]
Update fixed for me 👍

**Comment by awf0dz** [comment]
@iDevSpread This error is reproduced when closing and open (a.k.a. restarting) Atom. Happens to me every time but thanks, updating the package does work.

**Comment by cdesch** [comment]
@Awram What version did you update from? I'm experiencing the issue although the package is fully updated to `0.39.1`

**Comment by Awram** [comment]
@cdesch The package version I'm on right now is 0.40.2 so I don't think you are fully updated.

**Comment by Atreyu93** [comment]
The issue is fixed after the update, fine 👍

**Comment by C-Bouthoorn** [comment]
@cdesch You might need to update Atom too to update Pigments.

**Comment by ffxsam** [comment]
I'm unable to even update pigments for some reason (using Atom 1.19.2).

![image](https://user-images.githubusercontent.com/12532733/29394209-8a7d4e9c-82ce-11e7-8f53-0a857dccc5d3.png)

**Comment by jf0772256** [comment]
If you can't get the update to load try uninstalling and reinstalling the Pigments package.

**Comment by cdesch** [comment]
Upgrading atom and the package helped solve the issue. I'll check back at a
later time if the issue reoccurs, but upgrading the package and atom seemed
to fix the issue.

**Comment by Limboistik** [comment]
Updated to Atom 1.19.2 and this is happening to me too.

Tried uninstalling and reinstalling 0.40.2 Pigments, but still getting same error, any ideas?

**Comment by C-Bouthoorn** [comment]
Could you please click "Show output" and share that stack trace?

**Comment by nvaken** [comment]
For the record, I happened to bump into the original issue and just updated `pigments` to version 0.39.1 while having Atom 1.19.2, successfully. So I did not suffer the update bug reported above on this (outdated?) version. Weirdly enough, my Atom instance reports that now all my packages are up to date. So I'm unable to upgrade to the above reported version 0.40.2?

**Comment by ffxsam** [comment]
It's fixed for me now. Not sure what did it exactly.

**Comment by winfried-van-loon** [comment]
Just updated from a fairly old Atom version (1.17.2, if I recall correctly) to 1.19.2. Got the same error.

`Failed to activate the pigments package`

`Cannot find 'highlights-component' in the require cache.`

Stack trace:
```
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/Users/accountname/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/Users/accountname/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/Users/accountname/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

Just posting the stack trace as @C-Bouthoorn asked for it: No need to reopen the issue, will probably fix itself upon restart or plugin reinstall like it did for the people above.

**Comment by joao8809** [comment]
The issue is fixed after the update for me

**Comment by sajelgoel** [comment]
Try this: https://youtu.be/dRhXjz7-Rro
