### ISSUE TITLE
Error in the require cache

### ISSUE THREAD

**Issue by Leshovo** [abe33/atom-pigments#329]
Atom throw this error when initialize,
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -1:00.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-css-comb 3.3.1 
autoprefixer 3.7.1 
color-picker 2.2.5 
css-comb 2.5.0 
emmet 2.4.3 
file-icons 2.1.9 
highlight-selected 0.13.1 
language-postcss 1.3.1 
minimap 4.29.3 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.2 
pigments 0.39.1 
source-preview-postcss 0.1.4 
```

**Comment by nihiser** [comment]
Just need to update the package

https://github.com/abe33/atom-pigments/issues/328

**Comment by C-Bouthoorn** [comment]
Same as https://github.com/abe33/atom-pigments/issues/328
