### ISSUE TITLE
At Cannot find 'highlights-component' in the require cache.

### ISSUE THREAD

**Issue by cdesch** [abe33/atom-pigments#334]
in retrospect, I believe this is a duplicate of  #328

Reproduce

1. Open Atom

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.39.1

### Stack Trace

Failed to activate the pigments package

```
At Cannot find 'highlights-component' in the require cache.

Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Users/cj/Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/cj/Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/cj/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Users/cj/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Users/cj/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:15.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-ternjs 0.18.3 
autocomplete-elixir 1.5.14 
autocomplete-modules 1.6.10 
build-elixir 0.7.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
elixir-cmd 0.2.9 
elixir-pry 1.0.0 
es6-javascript 1.0.0 
file-icons 2.1.10 
highlight-selected 0.13.1 
iex 0.10.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-babel 2.69.0 
language-elixir 0.19.0 
language-erlang 3.2.0 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
script 3.15.0 
sync-settings 0.8.2 
```

**Comment by cdesch** [comment]
Closing as a duplicate of issue #328 

Please mark as duplicate
