### ISSUE TITLE
Failed to activate: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by philippbecker** [abe33/atom-pigments#34]
I can not enable the *pigments* package because of two errors which probably hang together.
Listed below are the two error reports that appeared to me in the last 10 days continuously.
But what really surprised me was the following notification: *The issue is already solved in #17.*

[Steps to reproduce:]

* Open editor **error 1**
* Open project folder **error 2**

**Atom Version**: 0.208.0 - 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.5.0 - v0.7.3

### Stack Trace 1

Failed to activate the pigments package

```
At Cannot read property 'querySelector' of null

TypeError: Cannot read property 'querySelector' of null
  at pigments-markers.ColorBufferElement.attach (/Users/philipp/.atom/packages/pigments/lib/color-buffer-element.coffee:150:52)
  at /Users/philipp/.atom/packages/pigments/lib/color-project.coffee:166:23
  at Workspace.module.exports.Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
  at ColorProject.module.exports.ColorProject.initializeBuffers (/Users/philipp/.atom/packages/pigments/lib/color-project.coffee:162:39)
  at new ColorProject (/Users/philipp/.atom/packages/pigments/lib/color-project.coffee:70:6)
  at Function.module.exports.ColorProject.deserialize (/Users/philipp/.atom/packages/pigments/lib/color-project.coffee:37:9)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:42:29)
  at Object.module.exports.activate (/Users/philipp/.atom/packages/pigments/lib/pigments.coffee:79:43)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Stack Trace 2

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/philipp/.atom/packages/pigments/lib/color-buffer-element.coffee:150

TypeError: Cannot read property 'querySelector' of null
  at pigments-markers.ColorBufferElement.attach (/Users/philipp/.atom/packages/pigments/lib/color-buffer-element.coffee:150:52)
  at /Users/philipp/.atom/packages/pigments/lib/color-buffer-element.coffee:70:55
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at atom-text-editor.TextEditorElement.attachedCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:101:27)
  at atom-pane.PaneElement.activeItemChanged (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activateNextItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:253:21)
  at Pane.module.exports.Pane.removeItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:370:16)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:602:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:641:21)
  at atom-workspace.atom.commands.add.core:close (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:314:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands 1

```
     -0:27.2.0 command-palette:toggle (input.hidden-input)
     -0:21.9.0 core:backspace (input.hidden-input)
     -0:19.3.0 editor:consolidate-selections (input.hidden-input)
     -0:19.3.0 core:cancel (input.hidden-input)
     -0:12.6.0 settings-view:open (input.hidden-input)
```

### Commands 2

```
  2x -0:23.6.0 application:new-file (atom-pane.pane.active)
     -0:08.9.0 project-manager:toggle (atom-pane.pane.active)
     -0:07.6.0 editor:consolidate-selections (input.hidden-input)
     -0:07.6.0 core:cancel (input.hidden-input)
     -0:05.7.0 settings-view:open (atom-pane.pane.active)
     -0:01.8.0 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "welcome",
      "symbols-tree-view",
      "color-picker",
      "git-tab-status"
    ]
  },
  "pigments": {
    "extendAutocompleteToVariables": true
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.7
git-log, v0.4.1
language-nginx, v0.5.3
language-rust, v0.4.3
language-slim, v0.4.0
linter, v0.12.7
linter-eslint, v0.5.9
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
linter-slim, v0.5.1
minimap, v4.10.0
minimap-git-diff, v4.1.3
pigments, v0.7.3
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by abe33** [comment]
My bad, I guess you have the `Shadow DOM` setting disabled, I forgot to check for that when attaching the markers container. I'll push a patch tonight.

**Comment by philippbecker** [comment]
@abe33 Some time ago I have disabled the shadow DOM due to font rendering issues, but **I forgot** to review the option in regard to the upcoming *Atom 1.0 release*.

Nevertheless, many thanks for the quick fix and keep up the good work!
*Pigments* is simply awesome :smile:
