### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by DataSyncID** [abe33/atom-pigments#350]
Running the latest version of ATOM and have encountered this error (the previous error was marked closed and fixed in 4.0.0, but I am using 5.0.0.). 

Steps to reproduce. 

1. Using Git CMD I ran: `git clone https://github.com/abe33/atom-pigments.git`
2. Then opened ATOM and it appeared. 

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Failed to activate the pigments package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-pigments/lib/expressions-registry.coffee:20:16)
    at /packages/atom-pigments/lib/variable-expressions.coffee:4:33)
    at /packages/atom-pigments/lib/variable-expressions.coffee:1:1)
    at /packages/atom-pigments/lib/variable-expressions.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-pigments/lib/color-project.coffee:53:36)
    at Object.activate (/packages/atom-pigments/lib/pigments.coffee:19:11)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.21.0-beta1/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.12 
atom-beautify 0.30.5 
atom-clock 0.1.15 
expose 0.14.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
open-recent 5.0.0 
pigments 0.40.2 
todo-show 2.0.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
console-panel 0.2.1 
emmet 2.4.3 
git-blame 1.2.2 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-liquid 0.6.0 
language-nsis 6.3.0 
linter 2.2.0 
linter-eslint 8.3.2 
linter-rubocop 2.1.1 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
project-manager 3.3.5 
```

**Comment by C-Bouthoorn** [comment]
You forgot to issue `apm install` or `npm install` in the source directory.
Also, the package would be much easier to install by entering `apm install pigments`.

**Comment by DataSyncID** [comment]
...Whelp... I'm an idiot, thanks for the help. That fixed it. I have to do the manual install way cause my work blocks straight installation via the command directly CMD for whatever reason, but running the "git" command through Git CMD and then running the install command after seems to work just fine. What a roundabout installation... Anyway, thanks for the help! At least it was simple!

**Comment by C-Bouthoorn** [comment]
You're welcome
