### ISSUE TITLE
Cannot Install Pigments (Failed to activate Pigments Package)

### ISSUE THREAD

**Issue by Siddharth-Parinayak** [abe33/atom-pigments#355]
**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8 Single Language
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Failed to activate the pigments package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:338:17)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:17.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autoclose-html 0.23.0 
pigments 0.40.2 
```

**Comment by C-Bouthoorn** [comment]
Doesn't seem to be related to Pigments. Try reinstalling Atom.
