### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by LHongLi** [abe33/atom-pigments#359]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:160

Error: kill EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.21.1/resources/app/src/task.js:148:31)
    at ColorBuffer.module.exports.ColorBuffer.terminateRunningTask (/packages/pigments/lib/color-buffer.coffee:166:35)
    at /packages/pigments/lib/color-buffer.coffee:33:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:626:38
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDidChangeSyncEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/display-layer.js:825:24)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:780:35
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:779:47)
    at TextBuffer.module.exports.TextBuffer.applyChange (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:762:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1001:22)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
    at TextEditor.module.exports.TextEditor.transact (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:1673:32)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.21.1/resources/app/src/text-editor-component.js:1630:30)
```

### Commands

```
     -2:08.6.0 snippets:expand (input.hidden-input)
     -2:08.6.0 editor:indent (input.hidden-input)
  8x -1:26.2.0 core:backspace (input.hidden-input)
     -1:24.2.0 core:save (input.hidden-input)
     -0:47 editor:newline (input.hidden-input)
  3x -0:42.8.0 core:save (input.hidden-input)
     -0:41.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:41.3.0 snippets:expand (input.hidden-input)
     -0:41.3.0 editor:indent (input.hidden-input)
     -0:35.5.0 core:move-left (input.hidden-input)
     -0:31.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:30.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:29.6.0 core:save (input.hidden-input)
     -0:24.7.0 editor:consolidate-selections (input.hidden-input)
     -0:24.7.0 core:cancel (input.hidden-input)
 14x -0:16.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atom-ternjs 0.18.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.13 
highlight-selected 0.13.1 
jquery-snippets 11.0.0 
language-postcss 1.3.1 
less-autocompile 1.0.0 
minimap 4.29.7 
pigments 0.40.2 
sass-autocompile 0.13.3 
simplified-chinese-menu 5.3.4 
```

**Comment by LHongLi** [comment]
在代码尾部填入分号时，出现错误

**Comment by C-Bouthoorn** [comment]
I'm sorry, but this does not seem to be related to Atom Pigments. Could you please try disabling all packages except Pigments to see if it still occurs?

**Google Translate:** 我很抱歉，但这似乎并不与Atom Pigments有关。 你可以尝试禁用除Atom Pigments之外的所有包，看看它是否仍然发生？

Also, could you please speak English? It makes communication a bit easier :smile:
