### ISSUE TITLE
pigments is causing problems in fuzzy-finder

### ISSUE THREAD

**Issue by pbgc** [abe33/atom-pigments#364]
Atom 1.21.1 (but it was happening in 1.21 and I think also in 1.20)
macOS 10.12.6

Fuzzy finder is sometimes (50%) giving: "Project is empty" in a non-empty project.

https://github.com/atom/fuzzy-finder/issues/309

When this happens I have these errors on the console:

```
Cannot find module 'atom' Error: Cannot find module 'atom'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object. (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:4:19)
at Object. (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:1:1)
at Object. (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:1:1)
at Module._compile (module.js:571:32)
at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object. (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:68:17)
at Object. (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:70:3)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
at run (bootstrap_node.js:424:7)
at startup (bootstrap_node.js:147:9)
at bootstrap_node.js:544:3
```

and

```
handler is not defined ReferenceError: handler is not defined
at process. (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:51:20)
at emitTwo (events.js:106:13)
at process.emit (events.js:191:7)
at process.nextTick (internal/child_process.js:752:12)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
```

So:
`at Object. (/Users/pbeck/.atom/packages/pigments/lib/tasks/load-paths-handler.coffee:4:19)`

It seems that it's a problem caused by pigments.

**Comment by C-Bouthoorn** [comment]
I understand that you think it's related to pigments, but what seems odd is that it says `atom` is not defined. Furthermore, the second error seems to originate from atom itself. Could you try reinstalling Atom?

**Comment by pbgc** [comment]
I opened this issue because that was what a member of the fuzzy-finder repo asked me to do ... but I tried to use the same setup with pigments disabled and I get the same result and errors ... so I'm going to close this issue. Thank!

**Comment by C-Bouthoorn** [comment]
You're welcome :smile:
