### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by meifangqi** [abe33/atom-pigments#373]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:160

Error: kill EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.23.1/resources/app/src/task.js:148:31)
    at ColorBuffer.module.exports.ColorBuffer.terminateRunningTask (/packages/pigments/lib/color-buffer.coffee:166:35)
    at /packages/pigments/lib/color-buffer.coffee:33:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at disposables.add.displayLayer.onDidChange.changes (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:588:26)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at DisplayLayer.emitDeferredChangeEvents (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/display-layer.js:833:26)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1682:30)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:18)
    at TextEditor.transact (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.23.1/resources/app/src/text-editor-component.js:1810:25)
```

### Commands

```
     -0:54.6.0 intentions:highlight (input.hidden-input)
     -0:54.5.0 core:paste (input.hidden-input)
     -0:36 markdown-writer:insert-new-line (input.hidden-input)
     -0:36 editor:newline (input.hidden-input)
     -0:35.6.0 intentions:highlight (input.hidden-input)
     -0:35.4.0 core:paste (input.hidden-input)
  2x -0:30.1.0 intentions:highlight (input.hidden-input)
     -0:29.5.0 editor:split-selections-into-lines (input.hidden-input)
     -0:29 core:move-left (input.hidden-input)
     -0:25.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
  8x -0:24.3.0 core:move-left (input.hidden-input)
     -0:23.4.0 core:move-right (input.hidden-input)
     -0:21.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:20.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:18.1.0 core:delete (input.hidden-input)
     -0:16.3.0 editor:consolidate-selections (input.hidden-input)
```

### Non-Core Packages

```
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.30.9 
atom-material-ui 2.0.6 
auto-fold 0.4.0 
auto-indent 0.5.0 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.15 
goto-definition 1.3.4 
highlight-selected 0.13.1 
insert-timestamp 0.2.4 
intentions 1.1.5 
language-awk 0.1.12 
language-gfm-enhanced 0.92.0 
language-markdown 0.25.1 
language-r 0.4.2 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-img-paste 0.3.9 
markdown-pdf 2.1.0 
markdown-preview-enhanced 0.15.1 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.0.1 
markdown-writer 2.7.3 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
remote-ftp 2.1.2 
script 3.17.3 
sync-settings 0.8.3 
trailing-spaces 0.4.0 
tree-view-finder 0.2.1 
vim-mode-plus 1.24.4 
```

**Comment by meifangqi** [comment]
How Can I resolve this problems?

**Comment by C-Bouthoorn** [comment]
What did you do to cause this issue?
