### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by ellehallal** [abe33/atom-pigments#374]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2408

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2408:65)
    at HTMLElement.screenPositionForPixelPosition (/app.asar/src/text-editor-element.js:247:32)
    at HTMLElement.ColorBufferElement.screenPositionForMouseEvent (/packages/pigments/lib/color-buffer-element.coffee:429:22)
    at HTMLElement.ColorBufferElement.colorMarkerForMouseEvent (/packages/pigments/lib/color-buffer-element.coffee:415:17)
    at Object.colorMarkerForMouseEvent (/packages/pigments/lib/pigments.coffee:221:25)
    at Object.shouldDisplayContextMenu (/packages/pigments/lib/pigments.coffee:215:5)
    at /packages/pigments/lib/pigments.coffee:111:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:167:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:100:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:189:33)
    at WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:251:44)
```

### Commands

```
     -1:34.3.0 core:move-left (input.hidden-input)
     -1:33.7.0 core:backspace (input.hidden-input)
     -1:33.2.0 editor:newline (input.hidden-input)
     -1:29.6.0 core:backspace (input.hidden-input)
  2x -1:29 core:move-right (input.hidden-input)
     -1:28.3.0 core:backspace (input.hidden-input)
  4x -1:27.5.0 core:move-right (input.hidden-input)
     -1:24.1.0 core:move-left (input.hidden-input)
     -1:23.5.0 core:backspace (input.hidden-input)
  2x -1:23 editor:newline (input.hidden-input)
     -1:19.7.0 core:save (input.hidden-input)
     -0:51.4.0 core:copy (input.hidden-input)
  2x -0:45 editor:newline (input.hidden-input)
     -0:43.9.0 core:paste (input.hidden-input)
     -0:25.7.0 editor:consolidate-selections (input.hidden-input)
     -0:25.7.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-material-ui 2.0.6 
autocomplete-paths 2.12.1 
color-picker 2.2.5 
emmet 2.4.3 
grammar-token-limit 0.1.1 
highlight-selected 0.13.1 
jquery-snippets 11.0.0 
livereload 0.4.4 
open-in-browser 0.5.2 
open-recent 5.0.0 
pigments 0.40.2 
seti-ui 1.9.0 
swackets 0.35.0 
```

**Comment by C-Bouthoorn** [comment]
Do you also have a piece of code for us that gave this error?

**Comment by itsellej** [comment]
I'm really sorry, I don't have the code. The error popped up when I was editing a .css file, if that helps.
