### ISSUE TITLE
Failed to activate the pigments package

### ISSUE THREAD

**Issue by dorellanaolivo** [abe33/atom-pigments#378]
SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\native-compile-cache.js:94:52)
    at Object.value [as .coffee] (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/dorel/AppData/Local/atom/app-1.23.3/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\native-compile-cache.js:66:33)
    at ColorBuffer.module.exports.ColorBuffer.scanBufferForColors (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-buffer.coffee:389:14)
    at ColorBuffer.module.exports.ColorBuffer.initialize (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-buffer.coffee:97:27)
    at new ColorBuffer (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-buffer.coffee:83:6)
    at ColorProject.module.exports.ColorProject.colorBufferForEditor (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-project.coffee:284:51)
    at file:///C:/Users/dorel/.atom/packages/pigments/lib/color-project.coffee:258:17
    at Workspace.observeTextEditors (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\workspace.js:725:15)
    at ColorProject.module.exports.ColorProject.initializeBuffers (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-project.coffee:254:39)
    at new ColorProject (file:///C:/Users/dorel/.atom/packages/pigments/lib/color-project.coffee:110:6)
    at Object.activate (file:///C:/Users/dorel/.atom/packages/pigments/lib/pigments.coffee:19:7)
    at Package.module.exports.Package.activateNow (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package.js:255:25)
    at C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package.js:227:38
    at Package.module.exports.Package.measure (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package.js:99:21)
    at C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package.js:220:32
    at Package.module.exports.Package.activate (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package.js:217:40)
    at PackageManager.activatePackage (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\package-manager.js:695:42)
    at C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\node_modules\settings-view\lib\package-manager.js:535:35
    at exit (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\dorel\AppData\Local\atom\app-1.23.3\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by luisgagocasas** [comment]
Error: Cannot find 'highlights-component' in the require cache.
    at requireCore (/home/luisgago/.atom/packages/pigments/lib/pigments.coffee:310:19)
    at Object.patchAtom (/home/luisgago/.atom/packages/pigments/lib/pigments.coffee:312:26)
    at Object.activate (/home/luisgago/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:255:25)
    at /usr/share/atom/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:647:50)
    at /usr/share/atom/resources/app/src/atom-environment.js:865:36

**Comment by benthurley82** [comment]
Atom updated itself to v1.23.3 on OSX and when it restarted I got this error "Failed to activate pigments package". The error said a bug has already been raised and pointed to here but the stack trace was different to the two above.

```
TypeError: Cannot read property 'length' of undefined
    at Function.Module._resolveLookupPaths (module.js:320:23)
    at Module._resolveFilename (module.js:461:31)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at requireCore (/Users/ben/.atom/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/Users/ben/.atom/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/Users/ben/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

**Comment by C-Bouthoorn** [comment]
@dorellanaolivo @benthurley82  Could you please share your Atom version, Pigments version, and OS?

@luisgagocasas Duplicate of #341 #335 #334 #329 #328 #318 #314 #201 #338

**Comment by preagan** [comment]
I'm getting what appeared to be the same error as benthurley82.
Upgrading my Pigments version 0.29.1  to version 0.40.2 seems to keep that error from coming up any longer.

Atom version: 1.23.3
OS +version:  Mac OS X 10.11.6

**Comment by benthurley82** [comment]
@C-Bouthoorn sorry I don't have the details with me right now, however, the problem sorted itself out after another round of updates. I think what I did before was update all the plugins and then update Atom. Then I got the problem with pigments not working and a message telling me about this ticket. I had another look for plugin updates and pigments said there was another update available, presumably because Atom was now at a later version? Anyway doing this third round of updates got everything working together without problems.
So problem solved for me now thanks.

**Comment by cahayabulan** [comment]
Atom 1.24.0 x64
OS X 10.13.3

Error: Cannot find 'highlights-component' in the require cache.
  at requireCore (/Users/kazuhiro/.atom/packages/pigments/lib/pigments.coffee:310:19)
  at Object.patchAtom (/Users/kazuhiro/.atom/packages/pigments/lib/pigments.coffee:312:26)
  at Object.activate (/Users/kazuhiro/.atom/packages/pigments/lib/pigments.coffee:16:6)
  at Package.activateNow (<embedded>:72380:33)
  at measure (<embedded>:72356:33)
  at Package.measure (<embedded>:72238:25)
  at activationPromise.Promise (<embedded>:72350:20)
  at Package.activate (<embedded>:72348:38)
  at PackageManager.activatePackage (<embedded>:25500:42)
  at config.transactAsync (<embedded>:25475:36)
  at Config.module.exports.Config.transactAsync (<embedded>:21896:24)
  at PackageManager.activatePackages (<embedded>:25473:23)
  at PackageManager.activate (<embedded>:25452:50)
  at loadStatePromise.loadState.then (<embedded>:1081:27)

**Comment by jpaulin** [comment]
Btw, I got this same error on Atom startup. 

What is the require cache trying to achieve? 
- preventing unnecessary (re)loads of code, or
- something else?

**Comment by C-Bouthoorn** [comment]
@cahayabulan This issue has already been answered quite some times now, the answer is to restart Atom. This problem is not related to Pigments, but is an issue within Atom itself.

**Comment by carlosescri** [comment]
FYI: I deleted Atom some time ago and today I decided to give it another chance. After installing, every time I restarted the app (on Mac) I got an error related to pigments. In my case I've removed the `.atom` folder inside my user folder and the error disappeared (I reinstalled Atom so it was not a problem for me). Hope this helps someone.

**Comment by C-Bouthoorn** [comment]
@LeszekWrobel That Stack Trace doesn't seem to originate from the `pigments` package. I suggest reinstalling Atom, since it seems some core files are corrupted.

**Comment by hugolpz** [comment]
0.39.0. Thanks to you I'am updating to the new one. Still new on Atom.
![screenshot from 2018-08-10 22-46-16](https://user-images.githubusercontent.com/1420189/43980636-3b2158f2-9cef-11e8-8f9b-e7ecf0a9cf9e.png)
