### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jameibumblebee** [abe33/atom-pigments#415]
[Enter steps to reproduce:]

1. Open PHP file.
2. Right click any area of opened PHP file.

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Enterprise N LTSC
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\User\AppData\Local\atom\app-1.33.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:75663)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:75595)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:74121)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:73581)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:72360)
    at Object.updateSync (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:126536)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:70218)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:91235)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:91426)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1192024)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:455231)
    at Pane.activateItem (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:457479)
    at TabBarView.t.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1141088)
```

### Commands

```
     -4:07.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-minify 0.8.0 
ide-css 0.3.2 
ide-html 0.4.2 
ide-json 0.2.1 
imagemin 1.6.1 
pigments 0.40.2 
```

**Comment by fishcharlie** [comment]
Having this same issue

**Comment by C-Bouthoorn** [comment]
Did you try to disable pigments and see if it happens again? The stack trace doesn't seem to mention pigments.

**Comment by LargePrime** [comment]
total noob here. same issue.
disabled pigments, = same issue.
uninstalled pigments, problem goes away

related https://github.com/atom/atom/issues/18343

**Comment by C-Bouthoorn** [comment]
Thanks for the related link. I'll quote from there: "I can confirm that it was about the package Pigments. This one can not handle compressed css style very wenn."

So this is something that'll have to be looked at when pigments revives again
