### ISSUE TITLE
Failed to load the pigments package

### ISSUE THREAD

**Issue by civilframe** [abe33/atom-pigments#42]
Steps to reproduce:
1. Went to Settings -> Install
2. Searched for pigments
3. Clicked Install

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.8.0
### Stack Trace

Failed to load the pigments package

```
At Cannot find module 'color'

Error: Cannot find module 'color'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/node_modules/css-color-function/lib/convert.js:3:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/node_modules/css-color-function/lib/index.js:2:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-expressions.coffee:1:12)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-expressions.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-search.coffee:3:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-search.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-project.coffee:7:15)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/color-project.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/pigments.coffee:2:16)
  at Object.<anonymous> (/Users/solo/.atom/packages/pigments/lib/pigments.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
  2x -1:13 core:move-up (atom-text-editor.editor.is-focused)
  4x -1:12.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:11.7.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -1:11.3.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -1:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:09.8.0 core:cut (atom-text-editor.editor.is-focused)
  2x -1:06.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:56.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:54.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:54.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:54.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:51.6.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:50.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
  2x -0:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
language-haml, v0.15.0
minimap, v4.10.0
pigments, v0.8.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Not sure about that, looks like some dependencies couldn't be installed, can you check if the `color` modules have been installed in the `node_modules` directory of pigments package? (you can find it in your home `.atom/packages` directory)

**Comment by LuckyLuky** [comment]
I have the same issue, I checked the ```.atom/packages``` directory and the color module has following modules installed: 
- ```color-convert```
- ```color-string```

I'm not sure if these are all that are required.

**Comment by daftpanda** [comment]
Same issue since today with several packages - atom got an update :(
and idea how to fix this?

**Comment by abe33** [comment]
@LuckyLuky, @daftpanda  Have you tried running `apm rebuild` or `apm rebuild-module-cache`?

**Comment by daftpanda** [comment]
@abe33 tried both, didn't fix the problem :(

**Comment by abe33** [comment]
You are on 1.0.15 right?

**Comment by daftpanda** [comment]
right :)
![image](https://cloud.githubusercontent.com/assets/14540591/9990876/3b0bb26e-6065-11e5-9914-fc86b88aa279.png)

**Comment by abe33** [comment]
I'm on 1.0.15 and didn't get that error, have you tried removing the `node_modules` directory in the package and run `apm install` manually in it?

**Comment by daftpanda** [comment]
did it, but didn't work aswell:

![image](https://cloud.githubusercontent.com/assets/14540591/9991103/5456f1dc-6067-11e5-97e9-e1ac27c7cfdf.png)

**Comment by abe33** [comment]
That's crazy... 
Is it the same module that can't be found each time or does it changes with consecutives installations? Also, is there some kind of error log during the install?

**Comment by daftpanda** [comment]
It's the same module that can't be found so far and nope, no error log while installing - just after it got installed again, the same error as above shows up...

**Comment by abe33** [comment]
I'm a bit at loss here, it's like some random package isn't installed properly, repeatedly, without any other kind of information. For instance minimatch is used by at least [scandal](https://github.com/atom/scandal) which is installed with Atom so I guess there's something deeper there. 
Can you try to `npm install minimatch` in pigments directory to see if it's a pb with the package/your config or with apm? It should be ok as there's no native extensions in it.

**Comment by daftpanda** [comment]
<code>apm install minimatch</code> in the pigments directory dropped the following:

![image](https://cloud.githubusercontent.com/assets/14540591/9992410/3c5f81c4-6072-11e5-813c-95f623785ae9.png)

**Comment by abe33** [comment]
@daftpanda Use `npm` instead of `apm` in this case specifically (`minimatch` is a node module and `apm` only install atom packages).

It looks like this issue occurs for many packages randomly (someone reported the same error in the minimap for another dependency, so it may be a much more broader issue with latest Atom release).

**Comment by daftpanda** [comment]
@abe33 thanks, but I already removed atom completely, reinstalled it and installed pigments again, but:

![image](https://cloud.githubusercontent.com/assets/14540591/9993271/2f67c5c6-6077-11e5-8615-7fbe2d1d75d0.png)

now it's another module xD
But yeah, I created a support topic about the whole problem:

https://discuss.atom.io/t/atom-throwing-several-failed-to-load-the-xyz-package-errors/20969

**Comment by abe33** [comment]
Thanks for your time :)

**Comment by daftpanda** [comment]
Well, I have to thank you for your time and efforts ;) Good job overall!

**Comment by LuckyLuky** [comment]
@abe33 You're right about the issue being broader, I have currently installed 4 community packages, ```save-session```, ```minimap```, ```php-debug``` and ```pigments```, and only ```save-session``` works, other packages always fail to load. I also have the latest version of Atom

**Comment by nathansobo** [comment]
Could this be an issue with npm?

**Comment by nathansobo** [comment]
@daftpanda Would you mind telling me which operating system you're using?

**Comment by daftpanda** [comment]
@nathansobo I'm running Windows 7 Ultimate 64bit

**Comment by malonehedges** [comment]
Happening with me as well. Occurred after I encountered #117

**Comment by C-Bouthoorn** [comment]
If I recall correctly, this problem was fixed in a commit not too long ago, so this can be closed.
