### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by Uberpaashaas** [abe33/atom-pigments#439]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package 0.40.2

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At internal/modules/cjs/loader.js:586

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:146745)
    at PigmentsProvider.module.exports.PigmentsProvider.findSuggestionsForPrefix (/packages/pigments/lib/pigments-provider.coffee:61:10)
    at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (/packages/pigments/lib/pigments-provider.coffee:42:20)
    at o.forEach.t (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:647501)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:647017)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:646755)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:655288)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:656379)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1213201)
    at TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:504695)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:492800)
    at TextEditor.transact (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:258317)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:94325)
```

### Commands

```
  7x -5:22.8.0 core:move-left (input.hidden-input)
     -5:20.7.0 core:backspace (input.hidden-input)
     -5:20.5.0 intentions:highlight (input.hidden-input)
     -5:20.2.0 core:save (input.hidden-input)
  3x -4:39.9.0 core:backspace (input.hidden-input)
     -4:33.5.0 core:move-left (input.hidden-input)
     -4:32.7.0 core:backspace (input.hidden-input)
     -4:28.3.0 core:move-right (input.hidden-input)
     -4:20.6.0 core:backspace (input.hidden-input)
     -4:12.3.0 intentions:highlight (input.hidden-input)
     -4:12.2.0 core:save (input.hidden-input)
     -4:01.3.0 editor:newline (input.hidden-input)
 13x -3:55 core:move-up (input.hidden-input)
  2x -3:52.6.0 editor:newline (input.hidden-input)
  2x -3:51.3.0 core:move-up (input.hidden-input)
  5x -3:44.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by Beeohat** [comment]
Please unsubscribe me from this thread.

**Comment by C-Bouthoorn** [comment]
I think something went wrong during the installation. Please try re-installing the plugin and/or atom.
