### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by maxguzenski** [abe33/atom-pigments#44]
Steps to reproduce below:

1. Just make a right click on any file

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/max/.atom/packages/pigments/lib/color-buffer.coffee:286

TypeError: Cannot read property 'getBoundingClientRect' of null
  at ColorBuffer.module.exports.ColorBuffer.pixelPositionForMouseEvent (/Users/max/.atom/packages/pigments/lib/color-buffer.coffee:286:65)
  at ColorBuffer.module.exports.ColorBuffer.screenPositionForMouseEvent (/Users/max/.atom/packages/pigments/lib/color-buffer.coffee:279:22)
  at ColorBuffer.module.exports.ColorBuffer.colorMarkerForMouseEvent (/Users/max/.atom/packages/pigments/lib/color-buffer.coffee:273:17)
  at Object.module.exports.colorMarkerForMouseEvent (/Users/max/.atom/packages/pigments/lib/pigments.coffee:154:18)
  at Object.module.exports.shouldDisplayContextMenu (/Users/max/.atom/packages/pigments/lib/pigments.coffee:149:5)
  at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/Users/max/.atom/packages/pigments/lib/pigments.coffee:132:36)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:108:25)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:166:27)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -4:05.1.0 core:backspace (input.hidden-input)
     -3:51.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai-syntax-for-one-dark.theme-one-dark-ui)
     -3:46.1.0 editor:consolidate-selections (input.hidden-input)
     -3:46.1.0 core:cancel (input.hidden-input)
     -3:05.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai-syntax-for-one-dark.theme-one-dark-ui)
  2x -3:02.9.0 core:move-down (input.hidden-input)
     -3:02.5.0 core:confirm (input.hidden-input)
     -3:02.5.0 pigments:show-palette (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai-syntax-for-one-dark.theme-one-dark-ui)
     -1:27.7.0 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
  3x -1:25.6.0 core:backspace (input.hidden-input)
     -1:24.9.0 editor:consolidate-selections (input.hidden-input)
     -1:24.9.0 core:cancel (input.hidden-input)
     -1:24.4.0 command-palette:toggle (div.settings-view.pane-item)
     -1:22.9.0 core:move-down (input.hidden-input)
     -1:20.6.0 core:confirm (input.hidden-input)
     -1:20.6.0 pigments:find-colors (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-php",
      "language-perl",
      "language-make",
      "language-mustache",
      "language-java",
      "distraction-free-mode",
    ],
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ]
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-sass, v0.1.0
color-picker, v2.0.7
file-icons, v1.5.8
language-rspec, v0.3.0
monokai-syntax-for-one-dark, v0.2.2
pigments, v0.8.0
project-manager, v1.15.10
react, v0.12.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by Remember2015** [comment]
the same exception in Atom 1.0 / Windows 8

**Comment by abe33** [comment]
Thanks for the report, it's my fault for assuming that everyone use the shadow DOM, a patch will come soon.

**Comment by jccguimaraes** [comment]
Had this on Atom 1.6.0 OSX and pigments 0.25.0

**Comment by abe33** [comment]
@jccguimaraes Could you describe me in which conditions this exception occured, and provides the stack trace to see if it comes from the same place.

**Comment by jccguimaraes** [comment]
basically i am scrolling in the code and somehow i do a double tap on the keypad and scroll at the same time. "works" every time... :(

**Comment by jccguimaraes** [comment]
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of nullColorBufferElement.pixelPositionForMouseEvent @ color-buffer-element.coffee:384ColorBufferElement.screenPositionForMouseEvent @ color-buffer-element.coffee:368ColorBufferElement.colorMarkerForMouseEvent @ color-buffer-element.coffee:362module.exports.colorMarkerForMouseEvent @ pigments.coffee:223module.exports.shouldDisplayContextMenu @ pigments.coffee:217atom.contextMenu.add.atom-text-editor.shouldDisplay @ pigments.coffee:166module.exports.ContextMenuManager.cloneItemForEvent @ /Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:110module.exports.ContextMenuManager.templateForEvent @ /Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:89module.exports.ContextMenuManager.showForEvent @ /Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:168module.exports.WindowEventHandler.handleDocumentContextmenu @ /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3`

**Comment by quarterto** [comment]
I'm also seeing this error thrown on right click. I have Shadow DOM enabled, so I suspect it's a different cause. This is the stack trace: 

```
TypeError: Cannot read property 'getBoundingClientRect' of null
    at pigments-markers.ColorBufferElement.pixelPositionForMouseEvent (/Users/matthew.brennan/.atom/packages/pigments/lib/color-buffer-element.coffee:384:54)
    at pigments-markers.ColorBufferElement.screenPositionForMouseEvent (/Users/matthew.brennan/.atom/packages/pigments/lib/color-buffer-element.coffee:368:22)
    at pigments-markers.ColorBufferElement.colorMarkerForMouseEvent (/Users/matthew.brennan/.atom/packages/pigments/lib/color-buffer-element.coffee:362:17)
    at Object.module.exports.colorMarkerForMouseEvent (/Users/matthew.brennan/.atom/packages/pigments/lib/pigments.coffee:223:25)
    at Object.module.exports.shouldDisplayContextMenu (/Users/matthew.brennan/.atom/packages/pigments/lib/pigments.coffee:217:5)
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/Users/matthew.brennan/.atom/packages/pigments/lib/pigments.coffee:166:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:110:19)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:89:33)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:168:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by NetOperatorWibby** [comment]
I didn't realize this was an old issue, but it just popped up for me.

**Comment by AshtonMeuser** [comment]
:+1:

**Comment by turigeza** [comment]
Same here 

`TypeError: Cannot read property 'getBoundingClientRect' of null
    at pigments-markers.ColorBufferElement.pixelPositionForMouseEvent (/Users/geza/.atom/packages/pigments/lib/color-buffer-element.coffee:568:54)
    at pigments-markers.ColorBufferElement.screenPositionForMouseEvent (/Users/geza/.atom/packages/pigments/lib/color-buffer-element.coffee:552:22)
    at pigments-markers.ColorBufferElement.colorMarkerForMouseEvent (/Users/geza/.atom/packages/pigments/lib/color-buffer-element.coffee:546:17)
    at Object.module.exports.colorMarkerForMouseEvent (/Users/geza/.atom/packages/pigments/lib/pigments.coffee:237:25)
    at Object.module.exports.shouldDisplayContextMenu (/Users/geza/.atom/packages/pigments/lib/pigments.coffee:231:5)
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (/Users/geza/.atom/packages/pigments/lib/pigments.coffee:180:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:110:19)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:89:33)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:168:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)`

**Comment by Its-its** [comment]
Sadly the same just started happening to me when I right click in any file editor.

**Atom Version**: 1.9.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.31.2


### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /C:/Users/Timothy/.atom/packages/pigments/lib/color-buffer-element.coffee:788

TypeError: Cannot read property 'getBoundingClientRect' of null
    at pigments-markers.ColorBufferElement.pixelPositionForMouseEvent (file:///C:/Users/Timothy/.atom/packages/pigments/lib/color-buffer-element.coffee:568:54)
    at pigments-markers.ColorBufferElement.screenPositionForMouseEvent (file:///C:/Users/Timothy/.atom/packages/pigments/lib/color-buffer-element.coffee:552:22)
    at pigments-markers.ColorBufferElement.colorMarkerForMouseEvent (file:///C:/Users/Timothy/.atom/packages/pigments/lib/color-buffer-element.coffee:546:17)
    at Object.module.exports.colorMarkerForMouseEvent (file:///C:/Users/Timothy/.atom/packages/pigments/lib/pigments.coffee:270:25)
    at Object.module.exports.shouldDisplayContextMenu (file:///C:/Users/Timothy/.atom/packages/pigments/lib/pigments.coffee:264:5)
    at Object.atom.contextMenu.add.atom-text-editor.shouldDisplay (file:///C:/Users/Timothy/.atom/packages/pigments/lib/pigments.coffee:213:36)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (C:\Users\Timothy\AppData\Local\atom\app-1.9.3\resources\app.asar\src\context-menu-manager.js:110:19)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (C:\Users\Timothy\AppData\Local\atom\app-1.9.3\resources\app.asar\src\context-menu-manager.js:89:33)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Timothy\AppData\Local\atom\app-1.9.3\resources\app.asar\src\context-menu-manager.js:168:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\Timothy\AppData\Local\atom\app-1.9.3\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\Timothy\AppData\Local\atom\app-1.9.3\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by NikkiDreams** [comment]
+1
