### ISSUE TITLE
Failed to activate the pigments package

### ISSUE THREAD

**Issue by ghanim-ga1206290** [abe33/atom-pigments#448]
Failed to activate the pigments package

Cannot read property 'startsWith' of undefined
Hide Stack Trace
TypeError: Cannot read property 'startsWith' of undefined
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:39:22)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155434)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at requireCore (/Users/GhanimAL_Ghanim/.atom/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (/Users/GhanimAL_Ghanim/.atom/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (/Users/GhanimAL_Ghanim/.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3194286)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3193698
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3191308)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3193558
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3193501)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382738)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382354
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332002)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382304)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381854)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717579
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718064)

**Comment by ManuelPeh76** [comment]
Cannot read property 'startsWith' of undefined

TypeError: Cannot read property 'startsWith' of undefined
    at Module._resolveFilename (\AppData\Local\atom\app-1.47.0\resources\electron.asar\common\reset-search-paths.js:39:22)
    at Function.get_Module._resolveFilename (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:155434)
    at Module.require (file:///AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:61:43)
    at require (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at requireCore (file:///.atom/packages/pigments/lib/pigments.coffee:295:7)
    at Object.patchAtom (file:///.atom/packages/pigments/lib/pigments.coffee:297:26)
    at Object.activate (file:///.atom/packages/pigments/lib/pigments.coffee:16:6)
    at Package.activateNow (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3298513)
    at \AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3297925
    at Package.measure (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3295535)
    at \AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3297785
    at new Promise (<anonymous>)
    at Package.activate (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:3297728)
    at PackageManager.activatePackage (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:382738)
    at \AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:382354
    at Config.transactAsync (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:332002)
    at PackageManager.activatePackages (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:382304)
    at PackageManager.activate (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:381854)
    at \AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:1:757178
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:1:757663)

**Comment by Cxarli** [comment]
update node and/or atom and/or apm and/or npm
