### ISSUE TITLE
Uncaught TypeError when I try to install.

### ISSUE THREAD

**Issue by bassamanator** [abe33/atom-pigments#457]
[Enter steps to reproduce:]

1. Goto install package in atom OR apm install pigments in terminal.
2. Result's in this error

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: "Manjaro Linux"
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.261.4

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /usr/lib/atom/node_modules/settings-view/lib/package-card.js:235

TypeError: Cannot read property 'version' of undefined
    at /usr/lib/atom/node_modules/settings-view/lib/package-card.js:235:35
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:319:18
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at ChildProcess.<anonymous> (/usr/lib/atom/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
     -4:29.9.0 termination:paste (div.)
     -4:10.7.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
atom-path-intellisense 1.2.2 
atom-python-run 0.9.7 
busy-signal 2.0.1 
color-indent 1.1.0 
color-picker 2.3.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.43 
goto-definition 1.3.4 
highlight-selected 0.17.0 
html-to-css 0.2.2 
ide-css 0.3.5 
ide-html 0.6.2 
ide-python 1.5.0 
intentions 1.1.5 
kite 0.186.0 
linter 3.1.0 
linter-eslint 8.5.5 
linter-ui-default 2.0.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
monokai 0.24.0 
p5js-snippets 0.4.4 
python-autopep8 0.1.3 
script 3.26.0 
space-tab 0.4.2 
TabNine 2.9.0 
termination 0.7.6 
todo-show 2.3.2 
tree-view-copy-relative-path 1.2.0 
```

**Comment by bassamanator** [comment]
Installed nodejs 14.x in the package manager and this fixed the issue. Node 12.18.4 was previously installed.
