### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by PavSidhu** [abe33/atom-pigments#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660

TypeError: Cannot read property 'getTokenIterator' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660:42)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1135:35)
  at ColorBuffer.module.exports.ColorBuffer.markerScopeIsIgnored (/Users/pavsidhu/.atom/packages/pigments/lib/color-buffer.coffee:337:35)
  at /Users/pavsidhu/.atom/packages/pigments/lib/color-buffer.coffee:294:41
  at Array.filter (native)
  at ColorBuffer.module.exports.ColorBuffer.findValidColorMarkers (/Users/pavsidhu/.atom/packages/pigments/lib/color-buffer.coffee:293:35)
  at pigments-markers.ColorBufferElement.updateMarkers (/Users/pavsidhu/.atom/packages/pigments/lib/color-buffer-element.coffee:116:28)
  at pigments-markers.ColorBufferElement.attachedCallback (/Users/pavsidhu/.atom/packages/pigments/lib/color-buffer-element.coffee:24:6)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:263:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:372:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:17.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:36 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:29.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "projectHome": "/Users/PavSidhu/Documents/Web\\ Development"
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
editor-stats, v0.17.0
emmet, v2.3.10
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.3.8
minimap, v4.10.0
pigments, v0.8.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for report, look like I overlooked some use cases.
Can you give me some details about the context in which this error occured? What kind of file were you working on? Did it occured on a specific action?

**Comment by abe33** [comment]
I've put some warning messages and I trap the error when it occurs. If you see these warning, could you please look at the grammar used in the editor (I log it with the warning).
