### ISSUE TITLE
I'm having an error installing pigments

### ISSUE THREAD

**Issue by BenTowali** [abe33/atom-pigments#465]
The error is Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/npm-cli' is not defined by "exports" in /usr/lib/node_modules/npm/package.json

Full output:

```
node:internal/modules/cjs/loader:479
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './bin/npm-cli' is not defined by "exports" in /usr/lib/node_modules/npm/package.json
    at new NodeError (node:internal/errors:329:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:320:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:545:3)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.node_module._findPath (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:141:32)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:911:27)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at new Install (/usr/lib/node_modules/atom-package-manager/lib/install.js:53:34)
    at Object.run (/usr/lib/node_modules/atom-package-manager/lib/apm-cli.js:240:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by Cxarli** [comment]
This seems more like an internal issue with Atom instead of a problem with this package. Please try re-installing Atom

**Comment by BenTowali** [comment]
This is an atom internal failure
