### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by guscastaneda** [abe33/atom-pigments#47]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.8.2

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:128

TypeError: Cannot read property 'path' of undefined
  at /Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:128:16
  at Palette.module.exports.Palette.eachColor (/Users/Boxerbrand/.atom/packages/pigments/lib/palette.coffee:23:28)
  at pigments-palette.PaletteElement.getFilesPalettes (/Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:127:14)
  at pigments-palette.PaletteElement.renderList (/Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:95:19)
  at /Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:53:8
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:557:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Object.subscriptions.add.subscribeTo.change [as __NONE__] (/Users/Boxerbrand/.atom/packages/pigments/lib/palette-element.coffee:62:19)
  at HTMLInputElement.listener (/Users/Boxerbrand/.atom/packages/minimap/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)

```

### Commands

```
     -3:47.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:46.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:46.8.0 pigments:find-colors (atom-text-editor.editor)
     -3:04.3.0 command-palette:toggle (ol.search-colors-results.results-view.list-tree.focusable-panel.has-collapsable-children)
  2x -3:01.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:00.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:59.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:59.2.0 pigments:show-palette (ol.search-colors-results.results-view.list-tree.focusable-panel.has-collapsable-children)
     -1:47.3.0 core:backspace (atom-text-editor#pigments.ignoredNames.editor.mini.is-focused)
     -1:41.8.0 core:save (atom-text-editor#pigments.ignoredNames.editor.mini.is-focused)
  2x -1:38.2.0 core:close (atom-pane.pane.active)
     -0:25.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:20.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 pigments:show-palette (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "genesis-snippets",
      "linter-tidy"
    ]
  },
  "pigments": {
    "sortPaletteColors": "by color",
    "groupPaletteColors": "by file",
    "ignoredNames": [
      "blog/*",
      "wp-includes/*"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-html-preview, v0.1.8
autocomplete-paths, v1.0.2
color-picker, v2.0.7
emmet, v2.3.11
linter, v1.1.0
linter-bootlint, v0.0.6
linter-csslint, v0.0.14
linter-haml, v0.4.0
linter-htmlhint, v0.0.16
linter-js-yaml, v1.1.1
linter-jshint, v0.1.7
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-scss-lint, v1.0.5
minimap, v4.10.1
pigments, v0.8.2
seti-icons, v0.3.0
tag, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, can you give me some details about what you were working on when it occured? Based on the report commands it looks like you edited a file, is that right?
