### ISSUE TITLE
uncugh error

### ISSUE THREAD

**Issue by Manjula6361** [abe33/atom-pigments#470]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\DELL\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\DELL\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893541)
    at get_manager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893643)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893769)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1118316)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1224088)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1222073)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:286551)
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.3.0 
autosave-onchange 1.5.1 
emmet 2.4.3 
git-plus 8.7.1 
open-in-browser 0.5.2 
pigments 0.40.6 
```

**Comment by Cxarli** [comment]
Try reinstalling. It seems something went wrong during the installation.
