### ISSUE TITLE
Issue with pigments 

### ISSUE THREAD

**Issue by aleixisp** [abe33/atom-pigments#471]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown macOS version
**Thrown From**: [pigments](ssh://git@github.com/abe33/atom-pigments) package 0.40.6

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:200

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at Task.send (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43868)
    at Task.start (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43700)
    at Function.Task.once (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42819)
    at /packages/pigments/lib/color-buffer.coffee:425:20
    at new Promise (<anonymous>)
    at ColorBuffer.module.exports.ColorBuffer.scanBufferForColors (/packages/pigments/lib/color-buffer.coffee:424:5)
    at /packages/pigments/lib/color-buffer.coffee:160:8
```

### Commands

```
  3x -0:52.7.0 core:backspace (input.hidden-input)
     -0:51 core:undo (input.hidden-input)
 24x -0:49.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
hex-view 1.0.1 
language-ejs 0.4.0 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.1.5 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by iannuttall** [comment]
I had the same issue today and fixed it by disabling the autoclose-html package.
