### ISSUE TITLE
Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

### ISSUE THREAD

**Issue by shelbyKiraM** [abe33/atom-pigments#480]
[Enter steps to reproduce:]

1. I have my webroot as my open project with between 2-3k files.
2. I open Command Palette, search `pigm` and select `Pigments: Show Palette`.
3. A new tab opens labelled Palette. When I try to swap to/close it, it takes a bit then throws this error.
4. When I try to click "Create issue …" I get this issue: https://github.com/atom/atom/issues/23662
5. Left Clicking on the word Palette on the new tabs opens a new tab, labeled Palette. Clicking the tab background or the close button does nothing.
6. Colors are rendering mostly properly.
7. The HSLA of a var that is just comma separated numbers isn't highlighting right but THAT should maybe be another issue (?):
```css
:root {
  --background-hsl: 231, 15%, 18%;
  --main-background: hsla(var(--background-hsl), 1);
}
```

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.2.1
**Thrown From**: [pigments](ssh://git@github.com/abe33/atom-pigments) package 0.40.6

### Stack Trace

Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

```
At /Users/user/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55

ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined
    at module.exports (/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55:5)
    at /packages/pigments/lib/palette-element.coffee:237:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at Object.pigmentsViewProvider (/packages/pigments/lib/pigments.coffee:206:25)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418494)
    at ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327908)
    at ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327373)
    at HTMLElement.getActiveView (/app.asar/src/pane-element.js:206:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:44:25)
    at HTMLElement.activated (/app.asar/src/pane-element.js:115:12)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187446)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188887)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:467610)
    at NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:885770)
    at NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:884656)
    at NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:884773)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:881090)
```

### Commands

```
     -7:03.6.0 intentions:highlight (input.hidden-input)
     -6:59.6.0 command-palette:toggle (input.hidden-input)
     -6:57.9.0 core:backspace (input.hidden-input)
     -6:54.8.0 pigments:show-palette (input.hidden-input)
     -1:37.9.0 auto-indent:apply (button.btn.icon.enablement.icon-playback-pause)
     -1:35.2.0 window:toggle-dev-tools (button.btn.icon.enablement.icon-playback-pause)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ctags 5.1.2 
atom-ide-ui 0.13.0 
atom-sass 0.4.0 
auto-indent 0.5.0 
browser-refresh-on-save 1.0.0 
busy-signal 2.0.1 
color-dict 0.7.0 
color-picker 2.3.0 
ctags-status 1.4.0 
dracula-syntax 3.0.2 
dracula-ui 0.6.0 
emoji-code 0.11.1 
file-type-icons 1.3.4 
file-types 1.0.1 
fix-indent-on-paste 0.1.1 
fold-functions 0.11.0 
git-control 0.9.0 
git-diff-details 1.4.0 
hex-to-rgba 2.0.0 
intentions 2.1.1 
last-cursor-position 1.2.0 
linter 3.4.0 
linter-csslint 2.0.6 
merge-conflicts 1.4.5 
minimap 4.40.0 
minimap-pigments 0.2.2 
open-in-github-app 0.2.6 
pigments 0.40.6 
prettier-atom 0.60.1 
remote-ftp 2.2.4 
set-syntax 0.4.0 
split-diff 1.6.1 
tag 0.5.0 
teletype 0.13.4 
text-manipulation 0.6.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.3 
url-encode 0.5.0 
var-that-color 0.4.1 
```

**Comment by UrsusMortiferum** [comment]
Hello,

I have similar issues with pigments:palette. 

### Description



### Steps to Reproduce

1. I open Command Palette, search pigm, and select Pigments: Show Palette.
2. A new tab opens labeled Palette. When I try to swap to/close it, it takes a bit and then throws this error.
3. Left Clicking on the word Palette on the new tabs opens a new tab labeled Palette. Clicking the tab background or the close button does nothing.
4. In my case, colors aren't rendering at all.

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.3.1
**Thrown From**: [pigments](ssh://git@github.com/abe33/atom-pigments) package 0.40.6


### Stack Trace

Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

```
At /Users/ursus_mortiferum/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55

ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined
    at module.exports (/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55:5)
    at /packages/pigments/lib/palette-element.coffee:237:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149229)
    at Object.pigmentsViewProvider (/packages/pigments/lib/pigments.coffee:206:25)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418346)
    at ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327939)
    at ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327404)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:139:33)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1189107)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:459674)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:461922)
    at TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1138283)
```

### Commands

```
     -1:14.6.0 intentions:highlight (input.hidden-input)
     -1:14.4.0 command-palette:toggle (input.hidden-input)
  2x -1:12.4.0 core:backspace (input.hidden-input)
     -1:09.8.0 core:move-left (input.hidden-input)
     -1:09.6.0 core:move-down (input.hidden-input)
     -1:09.2.0 core:confirm (input.hidden-input)
     -1:09.2.0 pigments:show-palette (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-discord 2.0.2 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
bracket-colorizer 1.4.0 
browser-plus 0.0.98 
busy-signal 2.0.1 
dracula-syntax 3.0.2 
dracula-ui 0.6.0 
emmet 2.4.3 
import 1.7.0 
intentions 2.1.1 
linter 3.4.0 
linter-csslint 2.0.6 
linter-htmlhint 1.6.3 
linter-tidy 2.4.0 
linter-ui-default 3.4.1 
livereload 0.4.4 
minimap 4.40.1 
minimap-pigments 0.2.2 
pane-layout-plus 0.7.4 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
script 3.32.2 
sync-settings 5.2.15 
```

**Comment by UrsusMortiferum** [comment]
#Update - I was able to resolve issues with not rendering colors :) + I was able to open the Palette tab without any problems; however, it's still empty.

In my case, creating a .pigments file helped

**Comment by UrsusMortiferum** [comment]
Overall, I was able to resolve all issues. After all, the palette was empty due to an incorrect database. @shelbyKiraM, I hope you will be able to come up with some solution for your case.

**Comment by tjdodson** [comment]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



Reaffirming this is still an issue and that I do not see any documentation on how to fix.

### Steps to Reproduce

1. `apm install atom-pigments`
2. open `Pigments: Show Pallette`

**Expected behavior:**


No errors

**Actual behavior:**


<img width="1818" alt="Screen Shot 2022-09-20 at 2 16 02 PM" src="https://user-images.githubusercontent.com/35269233/191345082-f3b55cab-541f-4aad-abe4-c466e12afbe5.png">


### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.6
**Thrown From**: [pigments](ssh://git@github.com/abe33/atom-pigments) package 0.40.6


### Stack Trace

Uncaught ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined

```
At /Users/t0d00bh/.atom/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55

ReferenceError: __CUSTOM_HTML_ELEMENTS_CLASSES__ is not defined
    at module.exports (/packages/pigments/node_modules/atom-utils/lib/register-or-update-element.js:55:5)
    at /packages/pigments/lib/palette-element.coffee:237:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at /packages/pigments/lib/palette-element.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149229)
    at Object.pigmentsViewProvider (/packages/pigments/lib/pigments.coffee:206:25)
    at Object.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418346)
    at ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327939)
    at ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327404)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:139:33)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1189107)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:459674)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:461922)
    at TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1138283)
```

### Commands

```
     -0:36.2.0 intentions:highlight (input.hidden-input)
  5x -0:36 core:undo (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:32.2.0 command-palette:toggle (input.hidden-input)
  8x -0:28.6.0 core:backspace (input.hidden-input)
  9x -0:22.4.0 core:move-down (input.hidden-input)
     -0:19.9.0 core:move-up (input.hidden-input)
     -0:19.5.0 core:confirm (input.hidden-input)
     -0:19.5.0 pigments:show-palette (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-comb 3.5.1 
atom-html-preview 0.2.7 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
autocomplete-python 1.17.1 
busy-signal 2.0.1 
color-picker 2.3.0 
docker 0.8.0 
double-tag 1.7.0 
drag-relative-path 1.2.3 
emmet 2.4.3 
file-icons 2.1.47 
highlight-selected 0.17.0 
Hydrogen 2.16.3 
intentions 2.1.1 
language-docker 1.1.8 
less-than-slash 0.20.0 
linter 3.4.0 
linter-csslint 2.0.6 
linter-docker 0.3.2 
linter-htmlhint 1.6.3 
linter-jshint 3.1.19 
linter-ui-default 3.4.1 
markdown-to-pdf 0.1.1 
merge-conflicts 1.4.5 
minimap 4.40.1 
minimap-cursorline 1.0.5 
pdf-view 0.73.0 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
prettier-atom 0.60.1 
script 3.32.2 
teletype 0.13.4 
todo-show 2.3.2 
```

### Additional Information
