### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getColorVariables' of null

### ISSUE THREAD

**Issue by kotarok** [abe33/atom-pigments#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.9.5
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getColorVariables' of null

```
At /Users/kotarok/.atom/packages/pigments/lib/pigments-provider.coffee:26

TypeError: Cannot read property 'getColorVariables' of null
  at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (/Users/kotarok/.atom/packages/pigments/lib/pigments-provider.coffee:26:27)
  at /Users/kotarok/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:152:45
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/kotarok/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:135:15)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/kotarok/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/kotarok/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:129:6)
  at /Users/kotarok/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
  5x -0:25.3.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:23.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:22.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:22.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:22.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:22.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:14.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:10.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:08.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "minimap"
    ]
  },
  "pigments": {
    "mergeColorDuplicates": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.24.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
color-picker, v1.7.0
docblockr, v0.6.3
emmet, v2.3.8
file-icons, v1.5.4
jshint, v1.3.5
linter, v0.12.1
pigments, v0.1.4
recent-files, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Can you give me some details on the context in which this error occurred?
Did you update pigments from the settings panel before the error occured?

**Comment by buunguyen** [comment]
Got same error every time I typed something (anything) in an SCSS file. Pigment 0.1.4 and was updated via the settings panel.

**Comment by abe33** [comment]
Do you have the same issue with the latest version?

**Comment by buunguyen** [comment]
@abe33 so far no issue.

**Comment by sbussard** [comment]
Could you push the change to Atom's repository? I'm getting this issue and atom says I have the latest version (0.9.3)

**Comment by abe33** [comment]
@sbussard Can you tell me more about the context in which this error occurred?

**Comment by oskarkrawczyk** [comment]
Autocomplete triggered the error

```
TypeError: Cannot read property 'getColorVariables' of null
  at PigmentsProvider.module.exports.PigmentsProvider.getSuggestions (/Users/oskar/.atom/packages/pigments/lib/pigments-provider.coffee:27:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

**Comment by sbussard** [comment]
@abe33: always, until I disabled it. 
I think @oskarkrawczyk is on to something.
