### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by likidu** [abe33/atom-pigments#63]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.9.2

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Marker.module.exports.Marker.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:59:43)
  at new ColorMarker (/Users/liki/.atom/packages/pigments/lib/color-marker.coffee:10:32)
  at processResults (/Users/liki/.atom/packages/pigments/lib/color-buffer.coffee:252:68)

```

### Commands

```
  2x -3:20 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:39.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:19.6.0 core:copy (atom-text-editor.editor.is-focused)
     -2:17.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:16.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
  6x -2:16 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:30.3.0 project-find:show (atom-text-editor.editor.is-focused)
  2x -1:28.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:55.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:54.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53 core:close (atom-text-editor.editor.mini.is-focused)
  2x -0:26 core:copy (atom-text-editor.editor.is-focused)
     -0:23 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:21.7.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-beautify, v0.28.8
atom-jade, v0.3.0
language-babel, v0.10.3
linter, v1.2.4
linter-eslint, v3.0.1
linter-stylint, v2.0.0
minimap, v4.12.1
php-twig, v4.0.0
pigments, v0.9.2
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by ivomarsan** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.9.2


### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /usr/share/atom/resources/app.asar/src/display-buffer.js:1098

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:1098:15)
    at Marker.module.exports.Marker.getHeadScreenPosition (/usr/share/atom/resources/app.asar/src/marker.js:179:33)
    at Marker.module.exports.Marker.onDidChange (/usr/share/atom/resources/app.asar/src/marker.js:59:43)
    at new ColorMarker (/home/ivomarsan/.atom/packages/pigments/lib/color-marker.coffee:18:42)
    at processResults (/home/ivomarsan/.atom/packages/pigments/lib/color-buffer.coffee:362:73)
```

### Commands

```
 13x -2:00.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:58 core:move-left (atom-text-editor.editor.is-focused)
  4x -1:57.7.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:56.8.0 core:paste (atom-text-editor.editor.is-focused)
 12x -1:56.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:55 core:move-left (atom-text-editor.editor.is-focused)
     -1:54.8.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:54.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:53.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:52.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:50 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:46.7.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:16.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:55 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.8.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.2
linter, v1.2.4
markdown-preview-plus, v1.6.0
mathjax-wrapper, v0.1.0
minimap, v4.12.1
pigments, v0.9.2
selector-to-tag, v0.4.1
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by abe33** [comment]
Can any of you give me a bit of context about this error? Like what action were you doing when the error occured?

**Comment by ricardograca** [comment]
I was looking at a file that contained a very long line when the error occurred when closing the file. In this case it was a minified version of bootstrap.css version 2.3.2.

**Comment by ivomarsan** [comment]
I opened a css file and closed when the error occurred. But I could work quietly after
