### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by diegognt** [abe33/atom-pigments#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.9.3

### Stack Trace

Failed to activate the minimap package

```
At Emitter has been disposed

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
    at ColorProject.module.exports.ColorProject.onDidCreateColorBuffer (/Users/diegonavarro/.atom/packages/pigments/lib/color-project.coffee:132:27)
    at ColorProject.module.exports.ColorProject.observeColorBuffers (/Users/diegonavarro/.atom/packages/pigments/lib/color-project.coffee:142:19)
    at PigmentsAPI.module.exports.PigmentsAPI.observeColorBuffers (/Users/diegonavarro/.atom/packages/pigments/lib/pigments-api.coffee:26:27)
    at Object.module.exports.initialize (/Users/diegonavarro/.atom/packages/minimap-pigments/lib/minimap-pigments.coffee:41:55)
    at Object.module.exports.activatePlugin (/Users/diegonavarro/.atom/packages/minimap-pigments/lib/minimap-pigments.coffee:37:21)
    at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/diegonavarro/.atom/packages/minimap/lib/mixins/plugin-management.coffee:92:16)
    at /Users/diegonavarro/.atom/packages/minimap/lib/mixins/plugin-management.coffee:112:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at Main.module.exports.PluginManagement.registerPluginControls (/Users/diegonavarro/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:55)
    at Main.module.exports.PluginManagement.registerPlugin (/Users/diegonavarro/.atom/packages/minimap/lib/mixins/plugin-management.coffee:38:14)
    at Object.module.exports.consumeMinimapServiceV1 (/Users/diegonavarro/.atom/packages/minimap-pigments/lib/minimap-pigments.coffee:19:27)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:377:65)
```

### Commands

```
     -1:15.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:15.7.0 refactor:done (atom-text-editor.editor.is-focused)
     -1:15.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:14.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:13.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:13.2.0 refactor:done (atom-text-editor.editor.is-focused)
     -1:13.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:12.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
  3x -1:05.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:57.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:57.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:56.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:56.6.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-polaris-syntax.theme-nucleus-dark-ui)
     -0:42.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-polaris-syntax.theme-nucleus-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "polaris-syntax"
    ],
    "disabledPackages": [
      "minimap-autohide",
      "language-SCSS",
      "jade-autocompile"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.8
atom-jade, v0.3.0
color-picker, v2.0.11
emmet, v2.3.12
js-refactor, v0.4.2
linter, v1.3.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.17
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-php, v1.0.2
linter-scss-lint, v2.0.0
minimap, v4.12.2
minimap-git-diff, v4.1.7
minimap-pigments, v0.1.2
minimap-selection, v4.3.0
nucleus-dark-ui, v0.1.3
pigments, v0.9.3
polaris-syntax, v0.1.0
refactor, v0.5.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Looks like a error that occurred on a package update, can you confirm?

**Comment by cyanpunk** [comment]
Confirmed, just caught this aswell after the update.

**Comment by abe33** [comment]
Ok I think I understand what happened, the patch will come soon (but won't get much opportunities to see the difference until I push a new minimap update).
