### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

### ISSUE THREAD

**Issue by smlombardi** [abe33/atom-pigments#73]
[Enter steps to reproduce below:]

1. ...select block in scss  file
2. ...edit >  cut

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:760

TypeError: Cannot read property 'getMaxScreenColumn' of undefined
    at SquareDotRenderer.module.exports.DotRenderer.render (/Users/stevelombardi/.atom/packages/pigments/lib/renderers/dot.coffee:19:27)
    at SquareDotRenderer.module.exports.SquareDotRenderer.render (/Users/stevelombardi/.atom/packages/pigments/lib/renderers/square-dot.coffee:17:55)
    at pigments-color-marker.ColorMarkerElement.render (/Users/stevelombardi/.atom/packages/pigments/lib/color-marker-element.coffee:90:29)
    at /Users/stevelombardi/.atom/packages/pigments/lib/color-marker-element.coffee:67:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at pigments-color-marker.ColorMarkerElement.setModel (/Users/stevelombardi/.atom/packages/pigments/lib/color-marker-element.coffee:65:42)
    at pigments-markers.ColorBufferElement.requestMarkerView (/Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:291:12)
    at pigments-markers.ColorBufferElement.updateMarkers (/Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:268:16)
    at /Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:88:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:120:32
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:481:22)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1558:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
```

### Commands

```
  3x -4:57.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -4:00.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:51.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:cut (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "SFTP-deployment",
      "autoprefixer",
      "deprecation-cop",
      "minimap"
    ],
    "themes": [
      "one-dark-ui",
      "duotone-blue-dark-syntax"
    ]
  },
  "pigments": {
    "ignoredScopes": [
      "\\.comment",
      "\\.text\\.html",
      "\\.source\\.js"
    ],
    "markerType": "square-dot"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.11
color-picker, v2.0.11
duotone-blue-dark-syntax, v1.0.1
emmet, v2.3.12
file-icons, v1.6.3
linter, v1.4.1
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-scss-lint, v2.0.0
pigments, v0.11.0
project-manager, v1.15.11
selection-counter, v0.1.1
tag, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hmm, seems like I can't reproduce this, do you happen to have updated pigments from within Atom before this error occured?

**Comment by burodepeper** [comment]
Got the same error.

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getMaxScreenColumn' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

TypeError: Cannot read property 'getMaxScreenColumn' of undefined
    at DotRenderer.module.exports.DotRenderer.render (/Users/david/.atom/packages/pigments/lib/renderers/dot.coffee:19:27)
    at pigments-color-marker.ColorMarkerElement.render (/Users/david/.atom/packages/pigments/lib/color-marker-element.coffee:90:29)
    at /Users/david/.atom/packages/pigments/lib/color-marker-element.coffee:67:24
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
    at pigments-color-marker.ColorMarkerElement.setModel (/Users/david/.atom/packages/pigments/lib/color-marker-element.coffee:65:42)
    at pigments-markers.ColorBufferElement.requestMarkerView (/Users/david/.atom/packages/pigments/lib/color-buffer-element.coffee:161:10)
    at pigments-markers.ColorBufferElement.updateMarkers (/Users/david/.atom/packages/pigments/lib/color-buffer-element.coffee:145:8)
    at /Users/david/.atom/packages/pigments/lib/color-buffer-element.coffee:48:8
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
```

### Commands

```
     -1:22.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:20.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:52 core:save (atom-text-editor.editor.is-focused)
     -0:51.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:50 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:49.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:49.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:49.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:36.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:28.2.0 core:save (atom-text-editor.editor.is-focused)
 10x -0:04.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:02.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  9x -0:02.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "minimal-syntax"
    ],
    "disabledPackages": [
      "go-to-line",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "link",
      "styleguide",
      "welcome",
      "spell-check",
      "linter-js-standard",
      "linter-csslint",
      "linter-tidy",
      "linter-tidy",
      "linter-coffeelint"
    ]
  },
  "pigments": {
    "markerType": "dot",
    "mergeColorDuplicates": true,
    "ignoredScopes": [
      "\\.comment",
      "\\.string"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
language-apache, v1.3.0
language-arduino, v0.3.1
linter, v1.4.3
linter-jshint, v1.1.5
linter-php, v1.0.3
minimal-syntax, v0.5.5
minimap, v4.13.2
minimap-git-diff, v4.1.8
pigments, v0.12.0
tabs-to-spaces, v0.11.1

# Dev
language-css, v0.33.0
language-gfm, v0.80.0
language-less, v0.28.2
language-php, v0.29.0
language-todo, v0.27.0
minimal-syntax, v0.5.5
```
