### ISSUE TITLE
Uncaught TypeError: Cannot read property 'invalidateScreenRangeCache' of null

### ISSUE THREAD

**Issue by smlombardi** [abe33/atom-pigments#74]
[Enter steps to reproduce below:]

1. ...scss file
2. ...called atom > beautify

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'invalidateScreenRangeCache' of null

```
At /Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:52

TypeError: Cannot read property 'invalidateScreenRangeCache' of null
  at /Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:52:27
  at Array.forEach (native)
  at /Users/stevelombardi/.atom/packages/pigments/lib/color-buffer-element.coffee:51:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1595:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1554:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:320:22)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:271:26
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
     -1:34.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:34.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:34.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:34.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:34.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:34.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:32.9.0 core:paste (atom-text-editor.editor.is-focused)
  7x -1:26 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:13.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:11.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:01.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:39.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.7.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "SFTP-deployment",
      "autoprefixer",
      "deprecation-cop",
      "minimap"
    ],
    "themes": [
      "one-dark-ui",
      "duotone-blue-dark-syntax"
    ]
  },
  "pigments": {
    "ignoredScopes": [
      "\\.comment",
      "\\.text\\.html",
      "\\.source\\.js"
    ],
    "markerType": "square-dot"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.11
color-picker, v2.0.11
duotone-blue-dark-syntax, v1.0.1
emmet, v2.3.12
file-icons, v1.6.3
linter, v1.4.1
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-jsonlint, v0.1.4
linter-less, v2.0.3
linter-scss-lint, v2.0.0
pigments, v0.11.0
project-manager, v1.15.11
selection-counter, v0.1.1
tag, v0.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi, same question as in #73

**Comment by smlombardi** [comment]
This seems to happen when I delete a large swath of text, in a scss file.
