### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by toastman** [abe33/atom-pigments#8]
Steps to reproduce :

1. Install package
2. Create *.scss file with some color variable (e.g $color-green:#29af09;)
3. Try to use "Pigments: Find Colors" 

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/toastman/.atom/packages/pigments/lib/color-search.coffee:48

TypeError: Cannot read property '1' of undefined
  at /Users/toastman/.atom/packages/pigments/lib/color-search.coffee:48:25
  at Workspace.module.exports.Workspace.scan (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:833:11)
  at ColorSearch.module.exports.ColorSearch.search (/Users/toastman/.atom/packages/pigments/lib/color-search.coffee:38:30)
  at pigments-color-results.module.exports.ColorResultsElement.setModel (/Users/toastman/.atom/packages/pigments/lib/color-results-element.coffee:63:18)
  at Object.createView (/Users/toastman/.atom/packages/pigments/lib/color-results-element.coffee:166:13)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:74:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:61:21)
  at /Users/toastman/.atom/packages/pigments/lib/pigments.coffee:88:18
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:433:22)
  at Object.module.exports.findColors (/Users/toastman/.atom/packages/pigments/lib/pigments.coffee:119:20)
  at atom-workspace.atom.commands.add.pigments:find-colors (/Users/toastman/.atom/packages/pigments/lib/pigments.coffee:79:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:32.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:32.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:32.1.0 editor:newline (atom-text-editor.editor)
     -0:29.8.0 application:new-file (atom-text-editor.editor)
     -0:28 core:save (atom-text-editor.editor.is-focused)
     -0:17.2.0 color-picker:open (atom-text-editor.editor.is-focused)
     -0:12.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:11.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:10.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:10.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.5.0 pigments:find-colors (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "change-case"
    ]
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.0
color-picker, v1.7.0
emmet, v2.3.8
file-icons, v1.5.5
javascript-snippets, v1.0.0
linter, v0.12.1
linter-eslint, v0.5.3
pigments, v0.2.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Do you still have this issue with the latest version?

**Comment by toastman** [comment]
Now it works fine, thanks )

**Comment by abe33** [comment]
cool :) I close the issue then

**Comment by seaside98** [comment]
@abe33 It just did this to me, same steps. It hasn't ever done it when I've viewed Find Colors before, but it just started.

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.8.0


### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/addison/.atom/packages/pigments/lib/color-search.coffee:48

TypeError: Cannot read property '1' of undefined
  at /Users/addison/.atom/packages/pigments/lib/color-search.coffee:48:25
  at Workspace.module.exports.Workspace.scan (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:879:11)
  at ColorSearch.module.exports.ColorSearch.search (/Users/addison/.atom/packages/pigments/lib/color-search.coffee:38:30)
  at pigments-color-results.module.exports.ColorResultsElement.setModel (/Users/addison/.atom/packages/pigments/lib/color-results-element.coffee:63:18)
  at Object.createView (/Users/addison/.atom/packages/pigments/lib/color-results-element.coffee:166:13)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:74:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:61:21)
  at /Users/addison/.atom/packages/pigments/lib/pigments.coffee:115:18
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:442:22)
  at Object.module.exports.findColors (/Users/addison/.atom/packages/pigments/lib/pigments.coffee:166:20)
  at atom-workspace.atom.commands.add.pigments:find-colors (/Users/addison/.atom/packages/pigments/lib/pigments.coffee:84:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.7.0 pigments:show-palette (atom-text-editor.editor)
     -0:18.9.0 core:close (atom-pane.pane.active)
     -0:17.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:15.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.1.0 pigments:find-colors (atom-text-editor.editor)
     -0:08.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:06.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 pigments:show-palette (atom-text-editor.editor)
     -0:04.3.0 core:close (atom-pane.pane.active)
     -0:03.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 pigments:find-colors (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/addison/Localhost",
    "disabledPackages": [
      "wrap-guide",
      "file-icons",
      "autoflow",
      "autocomplete-snippets"
    ]
  },
  "pigments": {
    "sourceNames": [
      "**/*.css"
    ],
    "mergeColorDuplicates": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-html-preview, v0.1.8
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
pigments, v0.8.0

# Dev
No dev packages
```
