### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by CFF** [abe33/atom-pigments#88]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.14.0
### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'push' of undefined
  at ColorProject.module.exports.ColorProject.appendPath (/Users/CFF/.atom/packages/pigments/lib/color-project.coffee:294:31)
  at /Users/CFF/.atom/packages/pigments/lib/color-buffer.coffee:37:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:185:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.setPath (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:313:20)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1019:12)
  at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:590:26)
  at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:571:16)
  at Pane.module.exports.Pane.saveActiveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:613:35)
  at atom-workspace.atom.commands.add.core:save-as (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:296:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -2:52.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:47 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:47 editor:newline (atom-text-editor.editor.is-focused)
     -2:09.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:08.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:08.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:03.2.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:55.9.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:55.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:55.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:55.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:45.5.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:37.7.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:32.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:31.7.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -0:54.4.0 core:save-as (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.11
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
emmet, v2.3.12
incremental-search, v5.0.1
linter, v1.5.1
pigments, v0.14.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi, can you give me more information about what actions led to this error?

**Comment by TheEnigmaBlade** [comment]
If it helps, I'm getting this issue when renaming files.

**Comment by C-Bouthoorn** [comment]
Due to inactivity, I think this is fixed now. Closing because of that reason.
