### ISSUE TITLE
Failed to activativate the pigments package

### ISSUE THREAD

**Issue by ernest33** [abe33/atom-pigments#94]
[Enter steps to reproduce below:]

1. Disable
2. Enable

**Atom Version**: 1.1.0-beta.0
**System**: Windows 7 Prof 64bits
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.16.1

### Stack Trace

Failed to activate the pigments package

```
At this.editorElement.onDidChangeScrollLeft is not a function

TypeError: this.editorElement.onDidChangeScrollLeft is not a function
  at pigments-markers.ColorBufferElement.setModel (C:\Users\ZFH582\.atom\packages\pigments\lib\color-buffer-element.coffee:44:39)
  at Object.createView (C:\Users\ZFH582\.atom\packages\pigments\lib\color-buffer-element.coffee:207:13)
  at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\view-registry.js:80:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\view-registry.js:65:21)
  at C:\Users\ZFH582\.atom\packages\pigments\lib\color-project.coffee:252:36
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:276:9)
  at ColorProject.module.exports.ColorProject.initializeBuffers (C:\Users\ZFH582\.atom\packages\pigments\lib\color-project.coffee:249:39)
  at new ColorProject (C:\Users\ZFH582\.atom\packages\pigments\lib\color-project.coffee:144:6)
  at Function.module.exports.ColorProject.deserialize (C:\Users\ZFH582\.atom\packages\pigments\lib\color-project.coffee:104:9)
  at DeserializerManager.module.exports.DeserializerManager.deserialize (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\deserializer-manager.js:42:29)
  at Object.module.exports.activate (C:\Users\ZFH582\.atom\packages\pigments\lib\pigments.coffee:90:43)
  at Package.module.exports.Package.activateNow (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:245:19)
  at C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:314:19
  at C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:587:20
  at Emitter.module.exports.Emitter.emit (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:772:29)
  at Config.module.exports.Config.setRawValue (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:564:19)
  at Config.module.exports.Config.set (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\config.js:356:12)
  at Package.module.exports.Package.enable (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:154:26)
  at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:143:14)
  at HTMLButtonElement.<anonymous> (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (C:\Users\ZFH582\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "steam-pirate-ui",
      "steam-pirate-syntax"
    ],
    "disabledPackages": [
      "editor-background",
      "project-colorize"
    ]
  },
  "pigments": {
    "mergeColorDuplicates": true
  }
}
```

### Installed Packages

```coffee
# User
bottom-dock, v0.3.5
color-tabs, v0.1.8
color-tabs-regex, v0.2.2
file-icon-supplement, v0.8.3
file-types, v0.5.1
flex-tool-bar, v0.5.0
foldername-tabs, v0.1.5
linter, v1.6.0
linter-js-standard, vundefined
linter-manager, v0.2.3
linter-php, v1.0.4
minimap, v4.13.4
neon-cursor, v0.2.0
neon-selection, v0.3.2
open-recent, v2.3.0
pigments, v0.16.1
project-manager, v2.6.1
steam-pirate-syntax, v0.3.0
steam-pirate-ui, v0.6.1
symbols-tree-view, v0.10.0
tool-bar, v0.1.9
tool-bar-almighty, v0.0.3
tool-bar-main, v0.0.8
tree-view-background, v0.4.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @ernest33, sorry for that, it comes from the deprecations fixes made to honor the latest master changes (see #92). 
I thought that fixing the engine version to >= 1.0.20 would be enough to protect against user with an older version to get the update but I didn't thought about people who built Atom from master and did not update since then.

I see two options here: 

1. Update Atom by pulling and then building against master
2. Downgrade pigments to version 0.15

**Comment by abe33** [comment]
Hi @ernest33, I believe v0.17.1 should have addressed this issue, let me know if I can close this issue.

**Comment by ernest33** [comment]
Hello @abe33 .
You can close this issue. Everything work good now :+1:
