### ISSUE TITLE
Uncaught TypeError: this.editorElement.onDidChangeScrollLeft is not a function

### ISSUE THREAD

**Issue by sergeyzozulya** [abe33/atom-pigments#96]
[Enter steps to reproduce below:]

1. Open file in fuzzy-finder
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [pigments](https://github.com/abe33/atom-pigments) package, v0.16.1

### Stack Trace

Uncaught TypeError: this.editorElement.onDidChangeScrollLeft is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/q/q.js:128

TypeError: this.editorElement.onDidChangeScrollLeft is not a function
  at pigments-markers.ColorBufferElement.setModel (/home/zozo/.atom/packages/pigments/lib/color-buffer-element.coffee:44:39)
  at Object.createView (/home/zozo/.atom/packages/pigments/lib/color-buffer-element.coffee:207:13)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:80:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:65:21)
  at /home/zozo/.atom/packages/pigments/lib/color-project.coffee:252:36
  at /usr/share/atom/resources/app.asar/src/workspace.js:281:16
  at /usr/share/atom/resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:352:27)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:313:14)
  at /usr/share/atom/resources/app.asar/src/workspace.js:489:16
  at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app.asar/node_modules/q/q.js:564:44
  at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -0:48.6.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:40.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:40.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:40 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.6.0 editor:join-lines (atom-pane.pane.active)
     -0:26.4.0 settings-view:open (atom-pane.pane.active)
  2x -0:25.6.0 key-binding-resolver:toggle (div.settings-view.pane-item)
     -0:10.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:08.7.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
     -0:07.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.5.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-seti-ui)
     -0:04.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "disabledPackages": [
      "dev-live-reload",
      "exception-reporting",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "open-on-github",
      "package-generator",
      "php-cs-fixer",
      "styleguide",
      "bookmarks",
      "autosave",
      "archive-view",
      "autoflow",
      "language-yaml",
      "project-sidebar",
      "project-view",
      "linter-php"
    ]
  },
  "pigments": {}
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
atom-autocomplete-php, v0.13.2
highlight-selected, v0.10.1
linter, v1.7.2
linter-phpcs, v1.1.3
minimap, v4.13.4
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
minimap-selection, v4.3.0
monokai, v0.18.0
pigments, v0.16.1
project-manager, v2.6.1
remote-sync, v3.1.2
seti-ui, v0.8.0
sync-settings, v0.6.0
terminal-panel, v1.14.1
up2date, v0.0.7

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @sergeyzozulya, how did you update pigments? v0.16.1 should not be available before Atom 1.0.20 gets released (see https://github.com/abe33/atom-pigments/blob/master/package.json#L18). 

This error is due to a change made on master that moves a lot of API from the text editor to its element, the patch that adressed these changes was released to fix the error for all the people using an Atom version built against master.

**Comment by sergeyzozulya** [comment]
Hi
I tried latest beta and it's updated all packages
After that I reverted back to 1.0.19
If this source of problems then sorry for bothering

_____________________

Sergey

**Comment by abe33** [comment]
@sergeyzozulya Yes, it seems like it, you should run `apm install pigments@0.16.0` to revert pigments too :)

**Comment by sergeyzozulya** [comment]
Didn't help
I have 0.16.0 installed and it still shows:

/usr/share/atom/resources/app.asar/node_modules/q/q.js:128
TypeError: this.editorElement.onDidChangeScrollLeft is not a function
at pigments-markers.ColorBufferElement.setModel
(/home/zozo/.atom/packages/pigments/lib/color-buffer-element.coffee:44:39)
at Object.createView
(/home/zozo/.atom/packages/pigments/lib/color-buffer-element.coffee:207:13)
at ViewRegistry.module.exports.ViewRegistry.createView
(/usr/share/atom/resources/app.asar/src/view-registry.js:80:72)
at ViewRegistry.module.exports.ViewRegistry.getView
(/usr/share/atom/resources/app.asar/src/view-registry.js:65:21)
at /home/zozo/.atom/packages/pigments/lib/color-project.coffee:263:40
at /usr/share/atom/resources/app.asar/src/workspace.js:281:16
at /usr/share/atom/resources/app.asar/src/workspace.js:342:18
at Emitter.module.exports.Emitter.emit
(/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
at PaneContainer.module.exports.PaneContainer.addedPaneItem
(/usr/share/atom/resources/app.asar/src/pane-container.js:352:27)
at /usr/share/atom/resources/app.asar/src/pane-container.js:339:26

_____________________

Sergey

**Comment by abe33** [comment]
@sergeyzozulya Oh sorry, 0.16 is the one I introduced the changes in, with 0.15 you'll be good. Again sorry for the mistake.

**Comment by sergeyzozulya** [comment]
thanks a lot, now it's fixed

_____________________

Sergey

**Comment by abe33** [comment]
Glad to hear that, I'll close the issue then.
